// @generated by protoc-gen-es v1.9.0
// @generated from file msp/azure/openai/assistants/v1/assistants.proto (package msp.azure.openai.assistants.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message msp.azure.openai.assistants.v1.Tool
 */
export const Tool = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.assistants.v1.Tool",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message msp.azure.openai.assistants.v1.Assistant
 */
export const Assistant = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.assistants.v1.Assistant",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "object", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "instruction", jsonName: "instructions", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "tools", kind: "message", T: Tool, repeated: true },
    { no: 9, name: "file_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
);

/**
 * @generated from message msp.azure.openai.assistants.v1.CreateAssistantRequest
 */
export const CreateAssistantRequest = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.assistants.v1.CreateAssistantRequest",
  () => [
    { no: 1, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "instruction", jsonName: "instructions", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "tools", kind: "message", T: Tool, repeated: true },
    { no: 6, name: "file_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 8, name: "temperature", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 9, name: "top_p", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 10, name: "response_format", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message msp.azure.openai.assistants.v1.ModifyAssistantRequest
 */
export const ModifyAssistantRequest = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.assistants.v1.ModifyAssistantRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "instruction", jsonName: "instructions", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "tools", kind: "message", T: Tool, repeated: true },
    { no: 5, name: "file_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
);

