// @generated by protoc-gen-es v1.9.0
// @generated from file msp/azure/openai/chat/v1/completions.proto (package msp.azure.openai.chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { ContentFilterChoiceResult, ContentFilterPromptResult, PromptFilterResult } from "../../v1/entity_pb.js";

/**
 * @generated from message msp.azure.openai.chat.v1.ChatCompletionRequest
 */
export const ChatCompletionRequest = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ChatCompletionRequest",
  () => [
    { no: 1, name: "temperature", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "top_p", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "stream", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "stops", jsonName: "stop", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "max_tokens", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "presence_penalty", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 7, name: "frequency_penalty", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 8, name: "logit_bias", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 2 /* ScalarType.FLOAT */} },
    { no: 9, name: "user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "messages", kind: "message", T: ChatCompletionRequestMessage, repeated: true },
    { no: 12, name: "n", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 13, name: "seed", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.ChatCompletionRequestMessage
 */
export const ChatCompletionRequestMessage = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ChatCompletionRequestMessage",
  () => [
    { no: 1, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.ChatCompletionResponse
 */
export const ChatCompletionResponse = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ChatCompletionResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "object", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "usage", kind: "message", T: Usage },
    { no: 6, name: "system_fingerprint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "prompt_filter_results", kind: "message", T: PromptFilterResult, repeated: true },
    { no: 8, name: "choices", kind: "message", T: Choice, repeated: true },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.Usage
 */
export const Usage = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.Usage",
  () => [
    { no: 1, name: "prompt_tokens", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "completion_tokens", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "total_tokens", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.Choice
 */
export const Choice = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.Choice",
  () => [
    { no: 1, name: "index", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "finish_reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "message", kind: "message", T: ChatCompletionResponseMessage },
    { no: 4, name: "content_filter_result", jsonName: "content_filter_results", kind: "message", T: ContentFilterChoiceResult },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.ChatCompletionResponseMessage
 */
export const ChatCompletionResponseMessage = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ChatCompletionResponseMessage",
  () => [
    { no: 1, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tool_calls", kind: "message", T: ChatCompletionMessageToolCall, repeated: true },
    { no: 4, name: "function_call", kind: "message", T: ChatCompletionFunctionCall },
    { no: 5, name: "context", kind: "message", T: AzureChatExtensionsMessageContext },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.ChatCompletionMessageToolCall
 */
export const ChatCompletionMessageToolCall = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ChatCompletionMessageToolCall",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "function", kind: "message", T: ChatCompletionMessageToolCall_Function },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.ChatCompletionMessageToolCall.Function
 */
export const ChatCompletionMessageToolCall_Function = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ChatCompletionMessageToolCall.Function",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "argument", jsonName: "arguments", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "ChatCompletionMessageToolCall_Function"},
);

/**
 * @generated from message msp.azure.openai.chat.v1.ChatCompletionFunctionCall
 */
export const ChatCompletionFunctionCall = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ChatCompletionFunctionCall",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "argument", jsonName: "arguments", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.AzureChatExtensionsMessageContext
 */
export const AzureChatExtensionsMessageContext = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.AzureChatExtensionsMessageContext",
  () => [
    { no: 1, name: "citations", kind: "message", T: AzureChatExtensionsMessageContext_Citation, repeated: true },
    { no: 2, name: "intent", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.AzureChatExtensionsMessageContext.Citation
 */
export const AzureChatExtensionsMessageContext_Citation = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.AzureChatExtensionsMessageContext.Citation",
  () => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "filepath", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "chunk_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AzureChatExtensionsMessageContext_Citation"},
);

/**
 * @generated from message msp.azure.openai.chat.v1.ErrorResponse
 */
export const ErrorResponse = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ErrorResponse",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "param", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "inner_error", kind: "message", T: ErrorResponse_InnerError },
  ],
);

/**
 * @generated from message msp.azure.openai.chat.v1.ErrorResponse.InnerError
 */
export const ErrorResponse_InnerError = /*@__PURE__*/ proto3.makeMessageType(
  "msp.azure.openai.chat.v1.ErrorResponse.InnerError",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content_filter_result", jsonName: "content_filter_results", kind: "message", T: ContentFilterPromptResult },
  ],
  {localName: "ErrorResponse_InnerError"},
);

