// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/images/v1/generations.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.images.v1;

public final class GenerationsProto {
  private GenerationsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      GenerationsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_images_v1_ImageGenerationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_images_v1_ImageGenerationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_images_v1_ImageGenerationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_images_v1_ImageGenerationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_images_v1_ImageResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_images_v1_ImageResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_images_v1_DalleContentFilterResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_images_v1_DalleContentFilterResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_images_v1_DalleFilterResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_images_v1_DalleFilterResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,msp/azure/openai/images/v1/generations" +
      ".proto\022\032msp.azure.openai.images.v1\032 msp/" +
      "azure/openai/v1/entity.proto\"\317\001\n\027ImageGe" +
      "nerationsRequest\022\026\n\006prompt\030\001 \001(\tR\006prompt" +
      "\022\014\n\001n\030\002 \001(\rR\001n\022\022\n\004size\030\003 \001(\tR\004size\022\'\n\017re" +
      "sponse_format\030\004 \001(\tR\016responseFormat\022!\n\014u" +
      "ser_context\030\005 \001(\tR\013userContext\022\030\n\007qualit" +
      "y\030\006 \001(\tR\007quality\022\024\n\005style\030\007 \001(\tR\005style\"q" +
      "\n\030ImageGenerationsResponse\022\030\n\007created\030\001 " +
      "\001(\004R\007created\022;\n\004data\030\002 \001(\0132\'.msp.azure.o" +
      "penai.images.v1.ImageResultR\004data\"\262\002\n\013Im" +
      "ageResult\022\020\n\003url\030\001 \001(\tR\003url\022\031\n\010b64_json\030" +
      "\002 \001(\tR\007b64Json\022k\n\025content_filter_result\030" +
      "\003 \001(\01324.msp.azure.openai.images.v1.Dalle" +
      "ContentFilterResultR\026content_filter_resu" +
      "lts\022%\n\016revised_prompt\030\004 \001(\tR\rrevisedProm" +
      "pt\022b\n\024prompt_filter_result\030\005 \001(\0132-.msp.a" +
      "zure.openai.images.v1.DalleFilterResultR" +
      "\025prompt_filter_results\"\307\002\n\030DalleContentF" +
      "ilterResult\022H\n\006sexual\030\001 \001(\01320.msp.azure." +
      "openai.v1.ContentFilterSeverityResultR\006s" +
      "exual\022L\n\010violence\030\002 \001(\01320.msp.azure.open" +
      "ai.v1.ContentFilterSeverityResultR\010viole" +
      "nce\022D\n\004hate\030\003 \001(\01320.msp.azure.openai.v1." +
      "ContentFilterSeverityResultR\004hate\022M\n\tsel" +
      "f_harm\030\004 \001(\01320.msp.azure.openai.v1.Conte" +
      "ntFilterSeverityResultR\010selfHarm\"\340\003\n\021Dal" +
      "leFilterResult\022H\n\006sexual\030\001 \001(\01320.msp.azu" +
      "re.openai.v1.ContentFilterSeverityResult" +
      "R\006sexual\022L\n\010violence\030\002 \001(\01320.msp.azure.o" +
      "penai.v1.ContentFilterSeverityResultR\010vi" +
      "olence\022D\n\004hate\030\003 \001(\01320.msp.azure.openai." +
      "v1.ContentFilterSeverityResultR\004hate\022M\n\t" +
      "self_harm\030\004 \001(\01320.msp.azure.openai.v1.Co" +
      "ntentFilterSeverityResultR\010selfHarm\022N\n\tp" +
      "rofanity\030\005 \001(\01320.msp.azure.openai.v1.Con" +
      "tentFilterDetectedResultR\tprofanity\022N\n\tj" +
      "ailbreak\030\006 \001(\01320.msp.azure.openai.v1.Con" +
      "tentFilterDetectedResultR\tjailbreakB\213\002\n\036" +
      "com.msp.azure.openai.images.v1B\020Generati" +
      "onsProtoP\001ZJgithub.com/anaregdesign/azur" +
      "e-proto/go/msp/azure/openai/images/v1;im" +
      "agesv1\242\002\004MAOI\252\002\032Msp.Azure.Openai.Images." +
      "V1\312\002\032Msp\\Azure\\Openai\\Images\\V1\342\002&Msp\\Az" +
      "ure\\Openai\\Images\\V1\\GPBMetadata\352\002\036Msp::" +
      "Azure::Openai::Images::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.msp.azure.openai.v1.EntityProto.getDescriptor(),
        });
    internal_static_msp_azure_openai_images_v1_ImageGenerationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msp_azure_openai_images_v1_ImageGenerationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_images_v1_ImageGenerationsRequest_descriptor,
        new java.lang.String[] { "Prompt", "N", "Size", "ResponseFormat", "UserContext", "Quality", "Style", });
    internal_static_msp_azure_openai_images_v1_ImageGenerationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msp_azure_openai_images_v1_ImageGenerationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_images_v1_ImageGenerationsResponse_descriptor,
        new java.lang.String[] { "Created", "Data", });
    internal_static_msp_azure_openai_images_v1_ImageResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_msp_azure_openai_images_v1_ImageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_images_v1_ImageResult_descriptor,
        new java.lang.String[] { "Url", "B64Json", "ContentFilterResult", "RevisedPrompt", "PromptFilterResult", });
    internal_static_msp_azure_openai_images_v1_DalleContentFilterResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_msp_azure_openai_images_v1_DalleContentFilterResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_images_v1_DalleContentFilterResult_descriptor,
        new java.lang.String[] { "Sexual", "Violence", "Hate", "SelfHarm", });
    internal_static_msp_azure_openai_images_v1_DalleFilterResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_msp_azure_openai_images_v1_DalleFilterResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_images_v1_DalleFilterResult_descriptor,
        new java.lang.String[] { "Sexual", "Violence", "Hate", "SelfHarm", "Profanity", "Jailbreak", });
    descriptor.resolveAllFeaturesImmutable();
    com.msp.azure.openai.v1.EntityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
