// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/chat/v1/completions.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.chat.v1;

/**
 * Protobuf type {@code msp.azure.openai.chat.v1.ChatCompletionFunctionCall}
 */
public final class ChatCompletionFunctionCall extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:msp.azure.openai.chat.v1.ChatCompletionFunctionCall)
    ChatCompletionFunctionCallOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      ChatCompletionFunctionCall.class.getName());
  }
  // Use ChatCompletionFunctionCall.newBuilder() to construct.
  private ChatCompletionFunctionCall(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChatCompletionFunctionCall() {
    name_ = "";
    argument_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msp.azure.openai.chat.v1.CompletionsProto.internal_static_msp_azure_openai_chat_v1_ChatCompletionFunctionCall_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msp.azure.openai.chat.v1.CompletionsProto.internal_static_msp_azure_openai_chat_v1_ChatCompletionFunctionCall_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall.class, com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARGUMENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object argument_ = "";
  /**
   * <code>string argument = 2 [json_name = "arguments"];</code>
   * @return The argument.
   */
  @java.lang.Override
  public java.lang.String getArgument() {
    java.lang.Object ref = argument_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      argument_ = s;
      return s;
    }
  }
  /**
   * <code>string argument = 2 [json_name = "arguments"];</code>
   * @return The bytes for argument.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArgumentBytes() {
    java.lang.Object ref = argument_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      argument_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(argument_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, argument_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(argument_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, argument_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall)) {
      return super.equals(obj);
    }
    com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall other = (com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getArgument()
        .equals(other.getArgument())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ARGUMENT_FIELD_NUMBER;
    hash = (53 * hash) + getArgument().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code msp.azure.openai.chat.v1.ChatCompletionFunctionCall}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:msp.azure.openai.chat.v1.ChatCompletionFunctionCall)
      com.msp.azure.openai.chat.v1.ChatCompletionFunctionCallOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msp.azure.openai.chat.v1.CompletionsProto.internal_static_msp_azure_openai_chat_v1_ChatCompletionFunctionCall_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msp.azure.openai.chat.v1.CompletionsProto.internal_static_msp_azure_openai_chat_v1_ChatCompletionFunctionCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall.class, com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall.Builder.class);
    }

    // Construct using com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      argument_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msp.azure.openai.chat.v1.CompletionsProto.internal_static_msp_azure_openai_chat_v1_ChatCompletionFunctionCall_descriptor;
    }

    @java.lang.Override
    public com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall getDefaultInstanceForType() {
      return com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall.getDefaultInstance();
    }

    @java.lang.Override
    public com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall build() {
      com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall buildPartial() {
      com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall result = new com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.argument_ = argument_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall) {
        return mergeFrom((com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall other) {
      if (other == com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getArgument().isEmpty()) {
        argument_ = other.argument_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              argument_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object argument_ = "";
    /**
     * <code>string argument = 2 [json_name = "arguments"];</code>
     * @return The argument.
     */
    public java.lang.String getArgument() {
      java.lang.Object ref = argument_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        argument_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string argument = 2 [json_name = "arguments"];</code>
     * @return The bytes for argument.
     */
    public com.google.protobuf.ByteString
        getArgumentBytes() {
      java.lang.Object ref = argument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        argument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string argument = 2 [json_name = "arguments"];</code>
     * @param value The argument to set.
     * @return This builder for chaining.
     */
    public Builder setArgument(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      argument_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string argument = 2 [json_name = "arguments"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArgument() {
      argument_ = getDefaultInstance().getArgument();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string argument = 2 [json_name = "arguments"];</code>
     * @param value The bytes for argument to set.
     * @return This builder for chaining.
     */
    public Builder setArgumentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      argument_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:msp.azure.openai.chat.v1.ChatCompletionFunctionCall)
  }

  // @@protoc_insertion_point(class_scope:msp.azure.openai.chat.v1.ChatCompletionFunctionCall)
  private static final com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall();
  }

  public static com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatCompletionFunctionCall>
      PARSER = new com.google.protobuf.AbstractParser<ChatCompletionFunctionCall>() {
    @java.lang.Override
    public ChatCompletionFunctionCall parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatCompletionFunctionCall> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatCompletionFunctionCall> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msp.azure.openai.chat.v1.ChatCompletionFunctionCall getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

