// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/chat/v1/completions.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.chat.v1;

public interface ChatCompletionRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msp.azure.openai.chat.v1.ChatCompletionRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role = 1 [json_name = "role"];</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 1 [json_name = "role"];</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
