// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/chat/v1/completions.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.chat.v1;

public interface CompletionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msp.azure.openai.chat.v1.CompletionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deployment_name = 1 [json_name = "deploymentName"];</code>
   * @return The deploymentName.
   */
  java.lang.String getDeploymentName();
  /**
   * <code>string deployment_name = 1 [json_name = "deploymentName"];</code>
   * @return The bytes for deploymentName.
   */
  com.google.protobuf.ByteString
      getDeploymentNameBytes();

  /**
   * <code>.msp.azure.openai.chat.v1.CompletionRequestBody body = 2 [json_name = "body"];</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>.msp.azure.openai.chat.v1.CompletionRequestBody body = 2 [json_name = "body"];</code>
   * @return The body.
   */
  com.msp.azure.openai.chat.v1.CompletionRequestBody getBody();
  /**
   * <code>.msp.azure.openai.chat.v1.CompletionRequestBody body = 2 [json_name = "body"];</code>
   */
  com.msp.azure.openai.chat.v1.CompletionRequestBodyOrBuilder getBodyOrBuilder();
}
