// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/v1/entity.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.v1;

/**
 * Protobuf type {@code msp.azure.openai.v1.ContentFilterChoiceResult}
 */
public final class ContentFilterChoiceResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:msp.azure.openai.v1.ContentFilterChoiceResult)
    ContentFilterChoiceResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      ContentFilterChoiceResult.class.getName());
  }
  // Use ContentFilterChoiceResult.newBuilder() to construct.
  private ContentFilterChoiceResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ContentFilterChoiceResult() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msp.azure.openai.v1.EntityProto.internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msp.azure.openai.v1.EntityProto.internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msp.azure.openai.v1.ContentFilterChoiceResult.class, com.msp.azure.openai.v1.ContentFilterChoiceResult.Builder.class);
  }

  private int bitField0_;
  public static final int SEXUAL_FIELD_NUMBER = 1;
  private com.msp.azure.openai.v1.ContentFilterSeverityResult sexual_;
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
   * @return Whether the sexual field is set.
   */
  @java.lang.Override
  public boolean hasSexual() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
   * @return The sexual.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResult getSexual() {
    return sexual_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : sexual_;
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getSexualOrBuilder() {
    return sexual_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : sexual_;
  }

  public static final int VIOLENCE_FIELD_NUMBER = 2;
  private com.msp.azure.openai.v1.ContentFilterSeverityResult violence_;
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
   * @return Whether the violence field is set.
   */
  @java.lang.Override
  public boolean hasViolence() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
   * @return The violence.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResult getViolence() {
    return violence_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : violence_;
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getViolenceOrBuilder() {
    return violence_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : violence_;
  }

  public static final int HATE_FIELD_NUMBER = 3;
  private com.msp.azure.openai.v1.ContentFilterSeverityResult hate_;
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
   * @return Whether the hate field is set.
   */
  @java.lang.Override
  public boolean hasHate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
   * @return The hate.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResult getHate() {
    return hate_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : hate_;
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getHateOrBuilder() {
    return hate_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : hate_;
  }

  public static final int SELF_HARM_FIELD_NUMBER = 4;
  private com.msp.azure.openai.v1.ContentFilterSeverityResult selfHarm_;
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
   * @return Whether the selfHarm field is set.
   */
  @java.lang.Override
  public boolean hasSelfHarm() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
   * @return The selfHarm.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResult getSelfHarm() {
    return selfHarm_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : selfHarm_;
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getSelfHarmOrBuilder() {
    return selfHarm_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : selfHarm_;
  }

  public static final int PROFANITY_FIELD_NUMBER = 5;
  private com.msp.azure.openai.v1.ContentFilterDetectedResult profanity_;
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
   * @return Whether the profanity field is set.
   */
  @java.lang.Override
  public boolean hasProfanity() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
   * @return The profanity.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterDetectedResult getProfanity() {
    return profanity_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : profanity_;
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder getProfanityOrBuilder() {
    return profanity_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : profanity_;
  }

  public static final int PROTECTED_MATERIAL_TEXT_FIELD_NUMBER = 6;
  private com.msp.azure.openai.v1.ContentFilterDetectedResult protectedMaterialText_;
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
   * @return Whether the protectedMaterialText field is set.
   */
  @java.lang.Override
  public boolean hasProtectedMaterialText() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
   * @return The protectedMaterialText.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterDetectedResult getProtectedMaterialText() {
    return protectedMaterialText_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : protectedMaterialText_;
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder getProtectedMaterialTextOrBuilder() {
    return protectedMaterialText_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : protectedMaterialText_;
  }

  public static final int PROTECTED_MATERIAL_CODE_FIELD_NUMBER = 7;
  private com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protectedMaterialCode_;
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
   * @return Whether the protectedMaterialCode field is set.
   */
  @java.lang.Override
  public boolean hasProtectedMaterialCode() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
   * @return The protectedMaterialCode.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult getProtectedMaterialCode() {
    return protectedMaterialCode_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.getDefaultInstance() : protectedMaterialCode_;
  }
  /**
   * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResultOrBuilder getProtectedMaterialCodeOrBuilder() {
    return protectedMaterialCode_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.getDefaultInstance() : protectedMaterialCode_;
  }

  public static final int ERROR_FIELD_NUMBER = 99;
  private com.msp.azure.openai.v1.ErrorBase error_;
  /**
   * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ErrorBase getError() {
    return error_ == null ? com.msp.azure.openai.v1.ErrorBase.getDefaultInstance() : error_;
  }
  /**
   * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.ErrorBaseOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.msp.azure.openai.v1.ErrorBase.getDefaultInstance() : error_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSexual());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getViolence());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getHate());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getSelfHarm());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getProfanity());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getProtectedMaterialText());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(7, getProtectedMaterialCode());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(99, getError());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSexual());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getViolence());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getHate());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSelfHarm());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getProfanity());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getProtectedMaterialText());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getProtectedMaterialCode());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(99, getError());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msp.azure.openai.v1.ContentFilterChoiceResult)) {
      return super.equals(obj);
    }
    com.msp.azure.openai.v1.ContentFilterChoiceResult other = (com.msp.azure.openai.v1.ContentFilterChoiceResult) obj;

    if (hasSexual() != other.hasSexual()) return false;
    if (hasSexual()) {
      if (!getSexual()
          .equals(other.getSexual())) return false;
    }
    if (hasViolence() != other.hasViolence()) return false;
    if (hasViolence()) {
      if (!getViolence()
          .equals(other.getViolence())) return false;
    }
    if (hasHate() != other.hasHate()) return false;
    if (hasHate()) {
      if (!getHate()
          .equals(other.getHate())) return false;
    }
    if (hasSelfHarm() != other.hasSelfHarm()) return false;
    if (hasSelfHarm()) {
      if (!getSelfHarm()
          .equals(other.getSelfHarm())) return false;
    }
    if (hasProfanity() != other.hasProfanity()) return false;
    if (hasProfanity()) {
      if (!getProfanity()
          .equals(other.getProfanity())) return false;
    }
    if (hasProtectedMaterialText() != other.hasProtectedMaterialText()) return false;
    if (hasProtectedMaterialText()) {
      if (!getProtectedMaterialText()
          .equals(other.getProtectedMaterialText())) return false;
    }
    if (hasProtectedMaterialCode() != other.hasProtectedMaterialCode()) return false;
    if (hasProtectedMaterialCode()) {
      if (!getProtectedMaterialCode()
          .equals(other.getProtectedMaterialCode())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSexual()) {
      hash = (37 * hash) + SEXUAL_FIELD_NUMBER;
      hash = (53 * hash) + getSexual().hashCode();
    }
    if (hasViolence()) {
      hash = (37 * hash) + VIOLENCE_FIELD_NUMBER;
      hash = (53 * hash) + getViolence().hashCode();
    }
    if (hasHate()) {
      hash = (37 * hash) + HATE_FIELD_NUMBER;
      hash = (53 * hash) + getHate().hashCode();
    }
    if (hasSelfHarm()) {
      hash = (37 * hash) + SELF_HARM_FIELD_NUMBER;
      hash = (53 * hash) + getSelfHarm().hashCode();
    }
    if (hasProfanity()) {
      hash = (37 * hash) + PROFANITY_FIELD_NUMBER;
      hash = (53 * hash) + getProfanity().hashCode();
    }
    if (hasProtectedMaterialText()) {
      hash = (37 * hash) + PROTECTED_MATERIAL_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getProtectedMaterialText().hashCode();
    }
    if (hasProtectedMaterialCode()) {
      hash = (37 * hash) + PROTECTED_MATERIAL_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getProtectedMaterialCode().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.v1.ContentFilterChoiceResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msp.azure.openai.v1.ContentFilterChoiceResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code msp.azure.openai.v1.ContentFilterChoiceResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:msp.azure.openai.v1.ContentFilterChoiceResult)
      com.msp.azure.openai.v1.ContentFilterChoiceResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msp.azure.openai.v1.EntityProto.internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msp.azure.openai.v1.EntityProto.internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msp.azure.openai.v1.ContentFilterChoiceResult.class, com.msp.azure.openai.v1.ContentFilterChoiceResult.Builder.class);
    }

    // Construct using com.msp.azure.openai.v1.ContentFilterChoiceResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getSexualFieldBuilder();
        getViolenceFieldBuilder();
        getHateFieldBuilder();
        getSelfHarmFieldBuilder();
        getProfanityFieldBuilder();
        getProtectedMaterialTextFieldBuilder();
        getProtectedMaterialCodeFieldBuilder();
        getErrorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sexual_ = null;
      if (sexualBuilder_ != null) {
        sexualBuilder_.dispose();
        sexualBuilder_ = null;
      }
      violence_ = null;
      if (violenceBuilder_ != null) {
        violenceBuilder_.dispose();
        violenceBuilder_ = null;
      }
      hate_ = null;
      if (hateBuilder_ != null) {
        hateBuilder_.dispose();
        hateBuilder_ = null;
      }
      selfHarm_ = null;
      if (selfHarmBuilder_ != null) {
        selfHarmBuilder_.dispose();
        selfHarmBuilder_ = null;
      }
      profanity_ = null;
      if (profanityBuilder_ != null) {
        profanityBuilder_.dispose();
        profanityBuilder_ = null;
      }
      protectedMaterialText_ = null;
      if (protectedMaterialTextBuilder_ != null) {
        protectedMaterialTextBuilder_.dispose();
        protectedMaterialTextBuilder_ = null;
      }
      protectedMaterialCode_ = null;
      if (protectedMaterialCodeBuilder_ != null) {
        protectedMaterialCodeBuilder_.dispose();
        protectedMaterialCodeBuilder_ = null;
      }
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msp.azure.openai.v1.EntityProto.internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_descriptor;
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.ContentFilterChoiceResult getDefaultInstanceForType() {
      return com.msp.azure.openai.v1.ContentFilterChoiceResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.ContentFilterChoiceResult build() {
      com.msp.azure.openai.v1.ContentFilterChoiceResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.ContentFilterChoiceResult buildPartial() {
      com.msp.azure.openai.v1.ContentFilterChoiceResult result = new com.msp.azure.openai.v1.ContentFilterChoiceResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.msp.azure.openai.v1.ContentFilterChoiceResult result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sexual_ = sexualBuilder_ == null
            ? sexual_
            : sexualBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.violence_ = violenceBuilder_ == null
            ? violence_
            : violenceBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.hate_ = hateBuilder_ == null
            ? hate_
            : hateBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.selfHarm_ = selfHarmBuilder_ == null
            ? selfHarm_
            : selfHarmBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.profanity_ = profanityBuilder_ == null
            ? profanity_
            : profanityBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.protectedMaterialText_ = protectedMaterialTextBuilder_ == null
            ? protectedMaterialText_
            : protectedMaterialTextBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.protectedMaterialCode_ = protectedMaterialCodeBuilder_ == null
            ? protectedMaterialCode_
            : protectedMaterialCodeBuilder_.build();
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msp.azure.openai.v1.ContentFilterChoiceResult) {
        return mergeFrom((com.msp.azure.openai.v1.ContentFilterChoiceResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msp.azure.openai.v1.ContentFilterChoiceResult other) {
      if (other == com.msp.azure.openai.v1.ContentFilterChoiceResult.getDefaultInstance()) return this;
      if (other.hasSexual()) {
        mergeSexual(other.getSexual());
      }
      if (other.hasViolence()) {
        mergeViolence(other.getViolence());
      }
      if (other.hasHate()) {
        mergeHate(other.getHate());
      }
      if (other.hasSelfHarm()) {
        mergeSelfHarm(other.getSelfHarm());
      }
      if (other.hasProfanity()) {
        mergeProfanity(other.getProfanity());
      }
      if (other.hasProtectedMaterialText()) {
        mergeProtectedMaterialText(other.getProtectedMaterialText());
      }
      if (other.hasProtectedMaterialCode()) {
        mergeProtectedMaterialCode(other.getProtectedMaterialCode());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSexualFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getViolenceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getHateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getSelfHarmFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getProfanityFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getProtectedMaterialTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getProtectedMaterialCodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 794: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 794
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.msp.azure.openai.v1.ContentFilterSeverityResult sexual_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> sexualBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     * @return Whether the sexual field is set.
     */
    public boolean hasSexual() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     * @return The sexual.
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult getSexual() {
      if (sexualBuilder_ == null) {
        return sexual_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : sexual_;
      } else {
        return sexualBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     */
    public Builder setSexual(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (sexualBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sexual_ = value;
      } else {
        sexualBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     */
    public Builder setSexual(
        com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder builderForValue) {
      if (sexualBuilder_ == null) {
        sexual_ = builderForValue.build();
      } else {
        sexualBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     */
    public Builder mergeSexual(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (sexualBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          sexual_ != null &&
          sexual_ != com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance()) {
          getSexualBuilder().mergeFrom(value);
        } else {
          sexual_ = value;
        }
      } else {
        sexualBuilder_.mergeFrom(value);
      }
      if (sexual_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     */
    public Builder clearSexual() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sexual_ = null;
      if (sexualBuilder_ != null) {
        sexualBuilder_.dispose();
        sexualBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder getSexualBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSexualFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getSexualOrBuilder() {
      if (sexualBuilder_ != null) {
        return sexualBuilder_.getMessageOrBuilder();
      } else {
        return sexual_ == null ?
            com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : sexual_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult sexual = 1 [json_name = "sexual"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> 
        getSexualFieldBuilder() {
      if (sexualBuilder_ == null) {
        sexualBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder>(
                getSexual(),
                getParentForChildren(),
                isClean());
        sexual_ = null;
      }
      return sexualBuilder_;
    }

    private com.msp.azure.openai.v1.ContentFilterSeverityResult violence_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> violenceBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     * @return Whether the violence field is set.
     */
    public boolean hasViolence() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     * @return The violence.
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult getViolence() {
      if (violenceBuilder_ == null) {
        return violence_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : violence_;
      } else {
        return violenceBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     */
    public Builder setViolence(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (violenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        violence_ = value;
      } else {
        violenceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     */
    public Builder setViolence(
        com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder builderForValue) {
      if (violenceBuilder_ == null) {
        violence_ = builderForValue.build();
      } else {
        violenceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     */
    public Builder mergeViolence(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (violenceBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          violence_ != null &&
          violence_ != com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance()) {
          getViolenceBuilder().mergeFrom(value);
        } else {
          violence_ = value;
        }
      } else {
        violenceBuilder_.mergeFrom(value);
      }
      if (violence_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     */
    public Builder clearViolence() {
      bitField0_ = (bitField0_ & ~0x00000002);
      violence_ = null;
      if (violenceBuilder_ != null) {
        violenceBuilder_.dispose();
        violenceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder getViolenceBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getViolenceFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getViolenceOrBuilder() {
      if (violenceBuilder_ != null) {
        return violenceBuilder_.getMessageOrBuilder();
      } else {
        return violence_ == null ?
            com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : violence_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult violence = 2 [json_name = "violence"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> 
        getViolenceFieldBuilder() {
      if (violenceBuilder_ == null) {
        violenceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder>(
                getViolence(),
                getParentForChildren(),
                isClean());
        violence_ = null;
      }
      return violenceBuilder_;
    }

    private com.msp.azure.openai.v1.ContentFilterSeverityResult hate_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> hateBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     * @return Whether the hate field is set.
     */
    public boolean hasHate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     * @return The hate.
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult getHate() {
      if (hateBuilder_ == null) {
        return hate_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : hate_;
      } else {
        return hateBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     */
    public Builder setHate(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (hateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hate_ = value;
      } else {
        hateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     */
    public Builder setHate(
        com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder builderForValue) {
      if (hateBuilder_ == null) {
        hate_ = builderForValue.build();
      } else {
        hateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     */
    public Builder mergeHate(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (hateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          hate_ != null &&
          hate_ != com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance()) {
          getHateBuilder().mergeFrom(value);
        } else {
          hate_ = value;
        }
      } else {
        hateBuilder_.mergeFrom(value);
      }
      if (hate_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     */
    public Builder clearHate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      hate_ = null;
      if (hateBuilder_ != null) {
        hateBuilder_.dispose();
        hateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder getHateBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getHateFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getHateOrBuilder() {
      if (hateBuilder_ != null) {
        return hateBuilder_.getMessageOrBuilder();
      } else {
        return hate_ == null ?
            com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : hate_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult hate = 3 [json_name = "hate"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> 
        getHateFieldBuilder() {
      if (hateBuilder_ == null) {
        hateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder>(
                getHate(),
                getParentForChildren(),
                isClean());
        hate_ = null;
      }
      return hateBuilder_;
    }

    private com.msp.azure.openai.v1.ContentFilterSeverityResult selfHarm_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> selfHarmBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     * @return Whether the selfHarm field is set.
     */
    public boolean hasSelfHarm() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     * @return The selfHarm.
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult getSelfHarm() {
      if (selfHarmBuilder_ == null) {
        return selfHarm_ == null ? com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : selfHarm_;
      } else {
        return selfHarmBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     */
    public Builder setSelfHarm(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (selfHarmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        selfHarm_ = value;
      } else {
        selfHarmBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     */
    public Builder setSelfHarm(
        com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder builderForValue) {
      if (selfHarmBuilder_ == null) {
        selfHarm_ = builderForValue.build();
      } else {
        selfHarmBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     */
    public Builder mergeSelfHarm(com.msp.azure.openai.v1.ContentFilterSeverityResult value) {
      if (selfHarmBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          selfHarm_ != null &&
          selfHarm_ != com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance()) {
          getSelfHarmBuilder().mergeFrom(value);
        } else {
          selfHarm_ = value;
        }
      } else {
        selfHarmBuilder_.mergeFrom(value);
      }
      if (selfHarm_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     */
    public Builder clearSelfHarm() {
      bitField0_ = (bitField0_ & ~0x00000008);
      selfHarm_ = null;
      if (selfHarmBuilder_ != null) {
        selfHarmBuilder_.dispose();
        selfHarmBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder getSelfHarmBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getSelfHarmFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder getSelfHarmOrBuilder() {
      if (selfHarmBuilder_ != null) {
        return selfHarmBuilder_.getMessageOrBuilder();
      } else {
        return selfHarm_ == null ?
            com.msp.azure.openai.v1.ContentFilterSeverityResult.getDefaultInstance() : selfHarm_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterSeverityResult self_harm = 4 [json_name = "selfHarm"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder> 
        getSelfHarmFieldBuilder() {
      if (selfHarmBuilder_ == null) {
        selfHarmBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ContentFilterSeverityResult, com.msp.azure.openai.v1.ContentFilterSeverityResult.Builder, com.msp.azure.openai.v1.ContentFilterSeverityResultOrBuilder>(
                getSelfHarm(),
                getParentForChildren(),
                isClean());
        selfHarm_ = null;
      }
      return selfHarmBuilder_;
    }

    private com.msp.azure.openai.v1.ContentFilterDetectedResult profanity_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterDetectedResult, com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder> profanityBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     * @return Whether the profanity field is set.
     */
    public boolean hasProfanity() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     * @return The profanity.
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedResult getProfanity() {
      if (profanityBuilder_ == null) {
        return profanity_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : profanity_;
      } else {
        return profanityBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     */
    public Builder setProfanity(com.msp.azure.openai.v1.ContentFilterDetectedResult value) {
      if (profanityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        profanity_ = value;
      } else {
        profanityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     */
    public Builder setProfanity(
        com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder builderForValue) {
      if (profanityBuilder_ == null) {
        profanity_ = builderForValue.build();
      } else {
        profanityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     */
    public Builder mergeProfanity(com.msp.azure.openai.v1.ContentFilterDetectedResult value) {
      if (profanityBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          profanity_ != null &&
          profanity_ != com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance()) {
          getProfanityBuilder().mergeFrom(value);
        } else {
          profanity_ = value;
        }
      } else {
        profanityBuilder_.mergeFrom(value);
      }
      if (profanity_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     */
    public Builder clearProfanity() {
      bitField0_ = (bitField0_ & ~0x00000010);
      profanity_ = null;
      if (profanityBuilder_ != null) {
        profanityBuilder_.dispose();
        profanityBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder getProfanityBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getProfanityFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder getProfanityOrBuilder() {
      if (profanityBuilder_ != null) {
        return profanityBuilder_.getMessageOrBuilder();
      } else {
        return profanity_ == null ?
            com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : profanity_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult profanity = 5 [json_name = "profanity"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterDetectedResult, com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder> 
        getProfanityFieldBuilder() {
      if (profanityBuilder_ == null) {
        profanityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ContentFilterDetectedResult, com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder>(
                getProfanity(),
                getParentForChildren(),
                isClean());
        profanity_ = null;
      }
      return profanityBuilder_;
    }

    private com.msp.azure.openai.v1.ContentFilterDetectedResult protectedMaterialText_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterDetectedResult, com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder> protectedMaterialTextBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     * @return Whether the protectedMaterialText field is set.
     */
    public boolean hasProtectedMaterialText() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     * @return The protectedMaterialText.
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedResult getProtectedMaterialText() {
      if (protectedMaterialTextBuilder_ == null) {
        return protectedMaterialText_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : protectedMaterialText_;
      } else {
        return protectedMaterialTextBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     */
    public Builder setProtectedMaterialText(com.msp.azure.openai.v1.ContentFilterDetectedResult value) {
      if (protectedMaterialTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        protectedMaterialText_ = value;
      } else {
        protectedMaterialTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     */
    public Builder setProtectedMaterialText(
        com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder builderForValue) {
      if (protectedMaterialTextBuilder_ == null) {
        protectedMaterialText_ = builderForValue.build();
      } else {
        protectedMaterialTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     */
    public Builder mergeProtectedMaterialText(com.msp.azure.openai.v1.ContentFilterDetectedResult value) {
      if (protectedMaterialTextBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          protectedMaterialText_ != null &&
          protectedMaterialText_ != com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance()) {
          getProtectedMaterialTextBuilder().mergeFrom(value);
        } else {
          protectedMaterialText_ = value;
        }
      } else {
        protectedMaterialTextBuilder_.mergeFrom(value);
      }
      if (protectedMaterialText_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     */
    public Builder clearProtectedMaterialText() {
      bitField0_ = (bitField0_ & ~0x00000020);
      protectedMaterialText_ = null;
      if (protectedMaterialTextBuilder_ != null) {
        protectedMaterialTextBuilder_.dispose();
        protectedMaterialTextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder getProtectedMaterialTextBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getProtectedMaterialTextFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder getProtectedMaterialTextOrBuilder() {
      if (protectedMaterialTextBuilder_ != null) {
        return protectedMaterialTextBuilder_.getMessageOrBuilder();
      } else {
        return protectedMaterialText_ == null ?
            com.msp.azure.openai.v1.ContentFilterDetectedResult.getDefaultInstance() : protectedMaterialText_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedResult protected_material_text = 6 [json_name = "protectedMaterialText"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterDetectedResult, com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder> 
        getProtectedMaterialTextFieldBuilder() {
      if (protectedMaterialTextBuilder_ == null) {
        protectedMaterialTextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ContentFilterDetectedResult, com.msp.azure.openai.v1.ContentFilterDetectedResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedResultOrBuilder>(
                getProtectedMaterialText(),
                getParentForChildren(),
                isClean());
        protectedMaterialText_ = null;
      }
      return protectedMaterialTextBuilder_;
    }

    private com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protectedMaterialCode_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult, com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResultOrBuilder> protectedMaterialCodeBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     * @return Whether the protectedMaterialCode field is set.
     */
    public boolean hasProtectedMaterialCode() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     * @return The protectedMaterialCode.
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult getProtectedMaterialCode() {
      if (protectedMaterialCodeBuilder_ == null) {
        return protectedMaterialCode_ == null ? com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.getDefaultInstance() : protectedMaterialCode_;
      } else {
        return protectedMaterialCodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     */
    public Builder setProtectedMaterialCode(com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult value) {
      if (protectedMaterialCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        protectedMaterialCode_ = value;
      } else {
        protectedMaterialCodeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     */
    public Builder setProtectedMaterialCode(
        com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.Builder builderForValue) {
      if (protectedMaterialCodeBuilder_ == null) {
        protectedMaterialCode_ = builderForValue.build();
      } else {
        protectedMaterialCodeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     */
    public Builder mergeProtectedMaterialCode(com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult value) {
      if (protectedMaterialCodeBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          protectedMaterialCode_ != null &&
          protectedMaterialCode_ != com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.getDefaultInstance()) {
          getProtectedMaterialCodeBuilder().mergeFrom(value);
        } else {
          protectedMaterialCode_ = value;
        }
      } else {
        protectedMaterialCodeBuilder_.mergeFrom(value);
      }
      if (protectedMaterialCode_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     */
    public Builder clearProtectedMaterialCode() {
      bitField0_ = (bitField0_ & ~0x00000040);
      protectedMaterialCode_ = null;
      if (protectedMaterialCodeBuilder_ != null) {
        protectedMaterialCodeBuilder_.dispose();
        protectedMaterialCodeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.Builder getProtectedMaterialCodeBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getProtectedMaterialCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     */
    public com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResultOrBuilder getProtectedMaterialCodeOrBuilder() {
      if (protectedMaterialCodeBuilder_ != null) {
        return protectedMaterialCodeBuilder_.getMessageOrBuilder();
      } else {
        return protectedMaterialCode_ == null ?
            com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.getDefaultInstance() : protectedMaterialCode_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult protected_material_code = 7 [json_name = "protectedMaterialCode"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult, com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResultOrBuilder> 
        getProtectedMaterialCodeFieldBuilder() {
      if (protectedMaterialCodeBuilder_ == null) {
        protectedMaterialCodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult, com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResult.Builder, com.msp.azure.openai.v1.ContentFilterDetectedWithCitationResultOrBuilder>(
                getProtectedMaterialCode(),
                getParentForChildren(),
                isClean());
        protectedMaterialCode_ = null;
      }
      return protectedMaterialCodeBuilder_;
    }

    private com.msp.azure.openai.v1.ErrorBase error_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ErrorBase, com.msp.azure.openai.v1.ErrorBase.Builder, com.msp.azure.openai.v1.ErrorBaseOrBuilder> errorBuilder_;
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     * @return The error.
     */
    public com.msp.azure.openai.v1.ErrorBase getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.msp.azure.openai.v1.ErrorBase.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     */
    public Builder setError(com.msp.azure.openai.v1.ErrorBase value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     */
    public Builder setError(
        com.msp.azure.openai.v1.ErrorBase.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     */
    public Builder mergeError(com.msp.azure.openai.v1.ErrorBase value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          error_ != null &&
          error_ != com.msp.azure.openai.v1.ErrorBase.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      if (error_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000080);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     */
    public com.msp.azure.openai.v1.ErrorBase.Builder getErrorBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     */
    public com.msp.azure.openai.v1.ErrorBaseOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.msp.azure.openai.v1.ErrorBase.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.ErrorBase error = 99 [json_name = "error"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.ErrorBase, com.msp.azure.openai.v1.ErrorBase.Builder, com.msp.azure.openai.v1.ErrorBaseOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.ErrorBase, com.msp.azure.openai.v1.ErrorBase.Builder, com.msp.azure.openai.v1.ErrorBaseOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:msp.azure.openai.v1.ContentFilterChoiceResult)
  }

  // @@protoc_insertion_point(class_scope:msp.azure.openai.v1.ContentFilterChoiceResult)
  private static final com.msp.azure.openai.v1.ContentFilterChoiceResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msp.azure.openai.v1.ContentFilterChoiceResult();
  }

  public static com.msp.azure.openai.v1.ContentFilterChoiceResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContentFilterChoiceResult>
      PARSER = new com.google.protobuf.AbstractParser<ContentFilterChoiceResult>() {
    @java.lang.Override
    public ContentFilterChoiceResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContentFilterChoiceResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContentFilterChoiceResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msp.azure.openai.v1.ContentFilterChoiceResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

