// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/v1/embeddings.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.v1;

/**
 * Protobuf type {@code msp.azure.openai.v1.EmbeddingResponse}
 */
public final class EmbeddingResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:msp.azure.openai.v1.EmbeddingResponse)
    EmbeddingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      EmbeddingResponse.class.getName());
  }
  // Use EmbeddingResponse.newBuilder() to construct.
  private EmbeddingResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmbeddingResponse() {
    object_ = "";
    model_ = "";
    data_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msp.azure.openai.v1.EmbeddingResponse.class, com.msp.azure.openai.v1.EmbeddingResponse.Builder.class);
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msp.azure.openai.v1.EmbeddingResponse.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 index = 1 [json_name = "index"];</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>string object = 2 [json_name = "object"];</code>
     * @return The object.
     */
    java.lang.String getObject();
    /**
     * <code>string object = 2 [json_name = "object"];</code>
     * @return The bytes for object.
     */
    com.google.protobuf.ByteString
        getObjectBytes();

    /**
     * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
     * @return A list containing the embedding.
     */
    java.util.List<java.lang.Float> getEmbeddingList();
    /**
     * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
     * @return The count of embedding.
     */
    int getEmbeddingCount();
    /**
     * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
     * @param index The index of the element to return.
     * @return The embedding at the given index.
     */
    float getEmbedding(int index);
  }
  /**
   * Protobuf type {@code msp.azure.openai.v1.EmbeddingResponse.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:msp.azure.openai.v1.EmbeddingResponse.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        Data.class.getName());
    }
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      object_ = "";
      embedding_ = emptyFloatList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msp.azure.openai.v1.EmbeddingResponse.Data.class, com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_ = 0;
    /**
     * <code>uint32 index = 1 [json_name = "index"];</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    public static final int OBJECT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object object_ = "";
    /**
     * <code>string object = 2 [json_name = "object"];</code>
     * @return The object.
     */
    @java.lang.Override
    public java.lang.String getObject() {
      java.lang.Object ref = object_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        object_ = s;
        return s;
      }
    }
    /**
     * <code>string object = 2 [json_name = "object"];</code>
     * @return The bytes for object.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectBytes() {
      java.lang.Object ref = object_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        object_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMBEDDING_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList embedding_ =
        emptyFloatList();
    /**
     * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
     * @return A list containing the embedding.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getEmbeddingList() {
      return embedding_;
    }
    /**
     * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
     * @return The count of embedding.
     */
    public int getEmbeddingCount() {
      return embedding_.size();
    }
    /**
     * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
     * @param index The index of the element to return.
     * @return The embedding at the given index.
     */
    public float getEmbedding(int index) {
      return embedding_.getFloat(index);
    }
    private int embeddingMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (index_ != 0) {
        output.writeUInt32(1, index_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(object_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, object_);
      }
      if (getEmbeddingList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(embeddingMemoizedSerializedSize);
      }
      for (int i = 0; i < embedding_.size(); i++) {
        output.writeFloatNoTag(embedding_.getFloat(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, index_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(object_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, object_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getEmbeddingList().size();
        size += dataSize;
        if (!getEmbeddingList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        embeddingMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.msp.azure.openai.v1.EmbeddingResponse.Data)) {
        return super.equals(obj);
      }
      com.msp.azure.openai.v1.EmbeddingResponse.Data other = (com.msp.azure.openai.v1.EmbeddingResponse.Data) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (!getObject()
          .equals(other.getObject())) return false;
      if (!getEmbeddingList()
          .equals(other.getEmbeddingList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + OBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getObject().hashCode();
      if (getEmbeddingCount() > 0) {
        hash = (37 * hash) + EMBEDDING_FIELD_NUMBER;
        hash = (53 * hash) + getEmbeddingList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.msp.azure.openai.v1.EmbeddingResponse.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msp.azure.openai.v1.EmbeddingResponse.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msp.azure.openai.v1.EmbeddingResponse.Data)
        com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.msp.azure.openai.v1.EmbeddingResponse.Data.class, com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder.class);
      }

      // Construct using com.msp.azure.openai.v1.EmbeddingResponse.Data.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        index_ = 0;
        object_ = "";
        embedding_ = emptyFloatList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Data_descriptor;
      }

      @java.lang.Override
      public com.msp.azure.openai.v1.EmbeddingResponse.Data getDefaultInstanceForType() {
        return com.msp.azure.openai.v1.EmbeddingResponse.Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.msp.azure.openai.v1.EmbeddingResponse.Data build() {
        com.msp.azure.openai.v1.EmbeddingResponse.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.msp.azure.openai.v1.EmbeddingResponse.Data buildPartial() {
        com.msp.azure.openai.v1.EmbeddingResponse.Data result = new com.msp.azure.openai.v1.EmbeddingResponse.Data(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.msp.azure.openai.v1.EmbeddingResponse.Data result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.index_ = index_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.object_ = object_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          embedding_.makeImmutable();
          result.embedding_ = embedding_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.msp.azure.openai.v1.EmbeddingResponse.Data) {
          return mergeFrom((com.msp.azure.openai.v1.EmbeddingResponse.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.msp.azure.openai.v1.EmbeddingResponse.Data other) {
        if (other == com.msp.azure.openai.v1.EmbeddingResponse.Data.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (!other.getObject().isEmpty()) {
          object_ = other.object_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.embedding_.isEmpty()) {
          if (embedding_.isEmpty()) {
            embedding_ = other.embedding_;
            embedding_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureEmbeddingIsMutable();
            embedding_.addAll(other.embedding_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                index_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                object_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 29: {
                float v = input.readFloat();
                ensureEmbeddingIsMutable();
                embedding_.addFloat(v);
                break;
              } // case 29
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureEmbeddingIsMutable(alloc / 4);
                while (input.getBytesUntilLimit() > 0) {
                  embedding_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int index_ ;
      /**
       * <code>uint32 index = 1 [json_name = "index"];</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <code>uint32 index = 1 [json_name = "index"];</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {

        index_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 index = 1 [json_name = "index"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object object_ = "";
      /**
       * <code>string object = 2 [json_name = "object"];</code>
       * @return The object.
       */
      public java.lang.String getObject() {
        java.lang.Object ref = object_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          object_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string object = 2 [json_name = "object"];</code>
       * @return The bytes for object.
       */
      public com.google.protobuf.ByteString
          getObjectBytes() {
        java.lang.Object ref = object_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          object_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string object = 2 [json_name = "object"];</code>
       * @param value The object to set.
       * @return This builder for chaining.
       */
      public Builder setObject(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        object_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string object = 2 [json_name = "object"];</code>
       * @return This builder for chaining.
       */
      public Builder clearObject() {
        object_ = getDefaultInstance().getObject();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string object = 2 [json_name = "object"];</code>
       * @param value The bytes for object to set.
       * @return This builder for chaining.
       */
      public Builder setObjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        object_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList embedding_ = emptyFloatList();
      private void ensureEmbeddingIsMutable() {
        if (!embedding_.isModifiable()) {
          embedding_ = makeMutableCopy(embedding_);
        }
        bitField0_ |= 0x00000004;
      }
      private void ensureEmbeddingIsMutable(int capacity) {
        if (!embedding_.isModifiable()) {
          embedding_ = makeMutableCopy(embedding_, capacity);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
       * @return A list containing the embedding.
       */
      public java.util.List<java.lang.Float>
          getEmbeddingList() {
        embedding_.makeImmutable();
        return embedding_;
      }
      /**
       * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
       * @return The count of embedding.
       */
      public int getEmbeddingCount() {
        return embedding_.size();
      }
      /**
       * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
       * @param index The index of the element to return.
       * @return The embedding at the given index.
       */
      public float getEmbedding(int index) {
        return embedding_.getFloat(index);
      }
      /**
       * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
       * @param index The index to set the value at.
       * @param value The embedding to set.
       * @return This builder for chaining.
       */
      public Builder setEmbedding(
          int index, float value) {

        ensureEmbeddingIsMutable();
        embedding_.setFloat(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
       * @param value The embedding to add.
       * @return This builder for chaining.
       */
      public Builder addEmbedding(float value) {

        ensureEmbeddingIsMutable();
        embedding_.addFloat(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
       * @param values The embedding to add.
       * @return This builder for chaining.
       */
      public Builder addAllEmbedding(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureEmbeddingIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, embedding_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float embedding = 3 [json_name = "embedding"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEmbedding() {
        embedding_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:msp.azure.openai.v1.EmbeddingResponse.Data)
    }

    // @@protoc_insertion_point(class_scope:msp.azure.openai.v1.EmbeddingResponse.Data)
    private static final com.msp.azure.openai.v1.EmbeddingResponse.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.msp.azure.openai.v1.EmbeddingResponse.Data();
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.EmbeddingResponse.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UsageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msp.azure.openai.v1.EmbeddingResponse.Usage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 prompt_tokens = 1 [json_name = "promptTokens"];</code>
     * @return The promptTokens.
     */
    int getPromptTokens();

    /**
     * <code>uint32 total_tokens = 2 [json_name = "totalTokens"];</code>
     * @return The totalTokens.
     */
    int getTotalTokens();
  }
  /**
   * Protobuf type {@code msp.azure.openai.v1.EmbeddingResponse.Usage}
   */
  public static final class Usage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:msp.azure.openai.v1.EmbeddingResponse.Usage)
      UsageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        Usage.class.getName());
    }
    // Use Usage.newBuilder() to construct.
    private Usage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Usage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Usage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Usage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msp.azure.openai.v1.EmbeddingResponse.Usage.class, com.msp.azure.openai.v1.EmbeddingResponse.Usage.Builder.class);
    }

    public static final int PROMPT_TOKENS_FIELD_NUMBER = 1;
    private int promptTokens_ = 0;
    /**
     * <code>uint32 prompt_tokens = 1 [json_name = "promptTokens"];</code>
     * @return The promptTokens.
     */
    @java.lang.Override
    public int getPromptTokens() {
      return promptTokens_;
    }

    public static final int TOTAL_TOKENS_FIELD_NUMBER = 2;
    private int totalTokens_ = 0;
    /**
     * <code>uint32 total_tokens = 2 [json_name = "totalTokens"];</code>
     * @return The totalTokens.
     */
    @java.lang.Override
    public int getTotalTokens() {
      return totalTokens_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (promptTokens_ != 0) {
        output.writeUInt32(1, promptTokens_);
      }
      if (totalTokens_ != 0) {
        output.writeUInt32(2, totalTokens_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (promptTokens_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, promptTokens_);
      }
      if (totalTokens_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, totalTokens_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.msp.azure.openai.v1.EmbeddingResponse.Usage)) {
        return super.equals(obj);
      }
      com.msp.azure.openai.v1.EmbeddingResponse.Usage other = (com.msp.azure.openai.v1.EmbeddingResponse.Usage) obj;

      if (getPromptTokens()
          != other.getPromptTokens()) return false;
      if (getTotalTokens()
          != other.getTotalTokens()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROMPT_TOKENS_FIELD_NUMBER;
      hash = (53 * hash) + getPromptTokens();
      hash = (37 * hash) + TOTAL_TOKENS_FIELD_NUMBER;
      hash = (53 * hash) + getTotalTokens();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.msp.azure.openai.v1.EmbeddingResponse.Usage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msp.azure.openai.v1.EmbeddingResponse.Usage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msp.azure.openai.v1.EmbeddingResponse.Usage)
        com.msp.azure.openai.v1.EmbeddingResponse.UsageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Usage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Usage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.msp.azure.openai.v1.EmbeddingResponse.Usage.class, com.msp.azure.openai.v1.EmbeddingResponse.Usage.Builder.class);
      }

      // Construct using com.msp.azure.openai.v1.EmbeddingResponse.Usage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        promptTokens_ = 0;
        totalTokens_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_Usage_descriptor;
      }

      @java.lang.Override
      public com.msp.azure.openai.v1.EmbeddingResponse.Usage getDefaultInstanceForType() {
        return com.msp.azure.openai.v1.EmbeddingResponse.Usage.getDefaultInstance();
      }

      @java.lang.Override
      public com.msp.azure.openai.v1.EmbeddingResponse.Usage build() {
        com.msp.azure.openai.v1.EmbeddingResponse.Usage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.msp.azure.openai.v1.EmbeddingResponse.Usage buildPartial() {
        com.msp.azure.openai.v1.EmbeddingResponse.Usage result = new com.msp.azure.openai.v1.EmbeddingResponse.Usage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.msp.azure.openai.v1.EmbeddingResponse.Usage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.promptTokens_ = promptTokens_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.totalTokens_ = totalTokens_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.msp.azure.openai.v1.EmbeddingResponse.Usage) {
          return mergeFrom((com.msp.azure.openai.v1.EmbeddingResponse.Usage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.msp.azure.openai.v1.EmbeddingResponse.Usage other) {
        if (other == com.msp.azure.openai.v1.EmbeddingResponse.Usage.getDefaultInstance()) return this;
        if (other.getPromptTokens() != 0) {
          setPromptTokens(other.getPromptTokens());
        }
        if (other.getTotalTokens() != 0) {
          setTotalTokens(other.getTotalTokens());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                promptTokens_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                totalTokens_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int promptTokens_ ;
      /**
       * <code>uint32 prompt_tokens = 1 [json_name = "promptTokens"];</code>
       * @return The promptTokens.
       */
      @java.lang.Override
      public int getPromptTokens() {
        return promptTokens_;
      }
      /**
       * <code>uint32 prompt_tokens = 1 [json_name = "promptTokens"];</code>
       * @param value The promptTokens to set.
       * @return This builder for chaining.
       */
      public Builder setPromptTokens(int value) {

        promptTokens_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 prompt_tokens = 1 [json_name = "promptTokens"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPromptTokens() {
        bitField0_ = (bitField0_ & ~0x00000001);
        promptTokens_ = 0;
        onChanged();
        return this;
      }

      private int totalTokens_ ;
      /**
       * <code>uint32 total_tokens = 2 [json_name = "totalTokens"];</code>
       * @return The totalTokens.
       */
      @java.lang.Override
      public int getTotalTokens() {
        return totalTokens_;
      }
      /**
       * <code>uint32 total_tokens = 2 [json_name = "totalTokens"];</code>
       * @param value The totalTokens to set.
       * @return This builder for chaining.
       */
      public Builder setTotalTokens(int value) {

        totalTokens_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 total_tokens = 2 [json_name = "totalTokens"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalTokens() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalTokens_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:msp.azure.openai.v1.EmbeddingResponse.Usage)
    }

    // @@protoc_insertion_point(class_scope:msp.azure.openai.v1.EmbeddingResponse.Usage)
    private static final com.msp.azure.openai.v1.EmbeddingResponse.Usage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.msp.azure.openai.v1.EmbeddingResponse.Usage();
    }

    public static com.msp.azure.openai.v1.EmbeddingResponse.Usage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Usage>
        PARSER = new com.google.protobuf.AbstractParser<Usage>() {
      @java.lang.Override
      public Usage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Usage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Usage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.EmbeddingResponse.Usage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int OBJECT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object object_ = "";
  /**
   * <code>string object = 1 [json_name = "object"];</code>
   * @return The object.
   */
  @java.lang.Override
  public java.lang.String getObject() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      object_ = s;
      return s;
    }
  }
  /**
   * <code>string object = 1 [json_name = "object"];</code>
   * @return The bytes for object.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectBytes() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      object_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object model_ = "";
  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.msp.azure.openai.v1.EmbeddingResponse.Data> data_;
  /**
   * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
   */
  @java.lang.Override
  public java.util.List<com.msp.azure.openai.v1.EmbeddingResponse.Data> getDataList() {
    return data_;
  }
  /**
   * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
   */
  @java.lang.Override
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.EmbeddingResponse.Data getData(int index) {
    return data_.get(index);
  }
  /**
   * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  public static final int USAGE_FIELD_NUMBER = 4;
  private com.msp.azure.openai.v1.EmbeddingResponse.Usage usage_;
  /**
   * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
   * @return Whether the usage field is set.
   */
  @java.lang.Override
  public boolean hasUsage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
   * @return The usage.
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.EmbeddingResponse.Usage getUsage() {
    return usage_ == null ? com.msp.azure.openai.v1.EmbeddingResponse.Usage.getDefaultInstance() : usage_;
  }
  /**
   * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.v1.EmbeddingResponse.UsageOrBuilder getUsageOrBuilder() {
    return usage_ == null ? com.msp.azure.openai.v1.EmbeddingResponse.Usage.getDefaultInstance() : usage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(object_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, object_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, model_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(3, data_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getUsage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(object_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, object_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, model_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, data_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUsage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msp.azure.openai.v1.EmbeddingResponse)) {
      return super.equals(obj);
    }
    com.msp.azure.openai.v1.EmbeddingResponse other = (com.msp.azure.openai.v1.EmbeddingResponse) obj;

    if (!getObject()
        .equals(other.getObject())) return false;
    if (!getModel()
        .equals(other.getModel())) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (hasUsage() != other.hasUsage()) return false;
    if (hasUsage()) {
      if (!getUsage()
          .equals(other.getUsage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getObject().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    if (hasUsage()) {
      hash = (37 * hash) + USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getUsage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.msp.azure.openai.v1.EmbeddingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.msp.azure.openai.v1.EmbeddingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.v1.EmbeddingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msp.azure.openai.v1.EmbeddingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code msp.azure.openai.v1.EmbeddingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:msp.azure.openai.v1.EmbeddingResponse)
      com.msp.azure.openai.v1.EmbeddingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msp.azure.openai.v1.EmbeddingResponse.class, com.msp.azure.openai.v1.EmbeddingResponse.Builder.class);
    }

    // Construct using com.msp.azure.openai.v1.EmbeddingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDataFieldBuilder();
        getUsageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      object_ = "";
      model_ = "";
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
      } else {
        data_ = null;
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msp.azure.openai.v1.EmbeddingsProto.internal_static_msp_azure_openai_v1_EmbeddingResponse_descriptor;
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.EmbeddingResponse getDefaultInstanceForType() {
      return com.msp.azure.openai.v1.EmbeddingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.EmbeddingResponse build() {
      com.msp.azure.openai.v1.EmbeddingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msp.azure.openai.v1.EmbeddingResponse buildPartial() {
      com.msp.azure.openai.v1.EmbeddingResponse result = new com.msp.azure.openai.v1.EmbeddingResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.msp.azure.openai.v1.EmbeddingResponse result) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
    }

    private void buildPartial0(com.msp.azure.openai.v1.EmbeddingResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.object_ = object_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.model_ = model_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.usage_ = usageBuilder_ == null
            ? usage_
            : usageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msp.azure.openai.v1.EmbeddingResponse) {
        return mergeFrom((com.msp.azure.openai.v1.EmbeddingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msp.azure.openai.v1.EmbeddingResponse other) {
      if (other == com.msp.azure.openai.v1.EmbeddingResponse.getDefaultInstance()) return this;
      if (!other.getObject().isEmpty()) {
        object_ = other.object_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      if (other.hasUsage()) {
        mergeUsage(other.getUsage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              object_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              model_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.msp.azure.openai.v1.EmbeddingResponse.Data m =
                  input.readMessage(
                      com.msp.azure.openai.v1.EmbeddingResponse.Data.parser(),
                      extensionRegistry);
              if (dataBuilder_ == null) {
                ensureDataIsMutable();
                data_.add(m);
              } else {
                dataBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getUsageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object object_ = "";
    /**
     * <code>string object = 1 [json_name = "object"];</code>
     * @return The object.
     */
    public java.lang.String getObject() {
      java.lang.Object ref = object_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        object_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object = 1 [json_name = "object"];</code>
     * @return The bytes for object.
     */
    public com.google.protobuf.ByteString
        getObjectBytes() {
      java.lang.Object ref = object_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        object_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object = 1 [json_name = "object"];</code>
     * @param value The object to set.
     * @return This builder for chaining.
     */
    public Builder setObject(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      object_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string object = 1 [json_name = "object"];</code>
     * @return This builder for chaining.
     */
    public Builder clearObject() {
      object_ = getDefaultInstance().getObject();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string object = 1 [json_name = "object"];</code>
     * @param value The bytes for object to set.
     * @return This builder for chaining.
     */
    public Builder setObjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      object_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <code>string model = 2 [json_name = "model"];</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model = 2 [json_name = "model"];</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model = 2 [json_name = "model"];</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      model_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2 [json_name = "model"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      model_ = getDefaultInstance().getModel();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2 [json_name = "model"];</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      model_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.msp.azure.openai.v1.EmbeddingResponse.Data> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        data_ = new java.util.ArrayList<com.msp.azure.openai.v1.EmbeddingResponse.Data>(data_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.msp.azure.openai.v1.EmbeddingResponse.Data, com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder, com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder> dataBuilder_;

    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public java.util.List<com.msp.azure.openai.v1.EmbeddingResponse.Data> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.Data getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder setData(
        int index, com.msp.azure.openai.v1.EmbeddingResponse.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder setData(
        int index, com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder addData(com.msp.azure.openai.v1.EmbeddingResponse.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder addData(
        int index, com.msp.azure.openai.v1.EmbeddingResponse.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder addData(
        com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder addData(
        int index, com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends com.msp.azure.openai.v1.EmbeddingResponse.Data> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public java.util.List<? extends com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          com.msp.azure.openai.v1.EmbeddingResponse.Data.getDefaultInstance());
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, com.msp.azure.openai.v1.EmbeddingResponse.Data.getDefaultInstance());
    }
    /**
     * <code>repeated .msp.azure.openai.v1.EmbeddingResponse.Data data = 3 [json_name = "data"];</code>
     */
    public java.util.List<com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.msp.azure.openai.v1.EmbeddingResponse.Data, com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder, com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.msp.azure.openai.v1.EmbeddingResponse.Data, com.msp.azure.openai.v1.EmbeddingResponse.Data.Builder, com.msp.azure.openai.v1.EmbeddingResponse.DataOrBuilder>(
                data_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.msp.azure.openai.v1.EmbeddingResponse.Usage usage_;
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.EmbeddingResponse.Usage, com.msp.azure.openai.v1.EmbeddingResponse.Usage.Builder, com.msp.azure.openai.v1.EmbeddingResponse.UsageOrBuilder> usageBuilder_;
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     * @return Whether the usage field is set.
     */
    public boolean hasUsage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     * @return The usage.
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.Usage getUsage() {
      if (usageBuilder_ == null) {
        return usage_ == null ? com.msp.azure.openai.v1.EmbeddingResponse.Usage.getDefaultInstance() : usage_;
      } else {
        return usageBuilder_.getMessage();
      }
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     */
    public Builder setUsage(com.msp.azure.openai.v1.EmbeddingResponse.Usage value) {
      if (usageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usage_ = value;
      } else {
        usageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     */
    public Builder setUsage(
        com.msp.azure.openai.v1.EmbeddingResponse.Usage.Builder builderForValue) {
      if (usageBuilder_ == null) {
        usage_ = builderForValue.build();
      } else {
        usageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     */
    public Builder mergeUsage(com.msp.azure.openai.v1.EmbeddingResponse.Usage value) {
      if (usageBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          usage_ != null &&
          usage_ != com.msp.azure.openai.v1.EmbeddingResponse.Usage.getDefaultInstance()) {
          getUsageBuilder().mergeFrom(value);
        } else {
          usage_ = value;
        }
      } else {
        usageBuilder_.mergeFrom(value);
      }
      if (usage_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     */
    public Builder clearUsage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.Usage.Builder getUsageBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getUsageFieldBuilder().getBuilder();
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     */
    public com.msp.azure.openai.v1.EmbeddingResponse.UsageOrBuilder getUsageOrBuilder() {
      if (usageBuilder_ != null) {
        return usageBuilder_.getMessageOrBuilder();
      } else {
        return usage_ == null ?
            com.msp.azure.openai.v1.EmbeddingResponse.Usage.getDefaultInstance() : usage_;
      }
    }
    /**
     * <code>.msp.azure.openai.v1.EmbeddingResponse.Usage usage = 4 [json_name = "usage"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.msp.azure.openai.v1.EmbeddingResponse.Usage, com.msp.azure.openai.v1.EmbeddingResponse.Usage.Builder, com.msp.azure.openai.v1.EmbeddingResponse.UsageOrBuilder> 
        getUsageFieldBuilder() {
      if (usageBuilder_ == null) {
        usageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.msp.azure.openai.v1.EmbeddingResponse.Usage, com.msp.azure.openai.v1.EmbeddingResponse.Usage.Builder, com.msp.azure.openai.v1.EmbeddingResponse.UsageOrBuilder>(
                getUsage(),
                getParentForChildren(),
                isClean());
        usage_ = null;
      }
      return usageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:msp.azure.openai.v1.EmbeddingResponse)
  }

  // @@protoc_insertion_point(class_scope:msp.azure.openai.v1.EmbeddingResponse)
  private static final com.msp.azure.openai.v1.EmbeddingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msp.azure.openai.v1.EmbeddingResponse();
  }

  public static com.msp.azure.openai.v1.EmbeddingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmbeddingResponse>
      PARSER = new com.google.protobuf.AbstractParser<EmbeddingResponse>() {
    @java.lang.Override
    public EmbeddingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmbeddingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmbeddingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msp.azure.openai.v1.EmbeddingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

