// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/v1/embeddings.proto
// Protobuf Java Version: 4.27.1

package com.msp.azure.openai.v1;

public interface EmbeddingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msp.azure.openai.v1.EmbeddingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @return The input.
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @return The bytes for input.
   */
  com.google.protobuf.ByteString
      getInputBytes();

  /**
   * <code>string user = 2 [json_name = "user"];</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <code>string user = 2 [json_name = "user"];</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string input_type = 3 [json_name = "inputType"];</code>
   * @return The inputType.
   */
  java.lang.String getInputType();
  /**
   * <code>string input_type = 3 [json_name = "inputType"];</code>
   * @return The bytes for inputType.
   */
  com.google.protobuf.ByteString
      getInputTypeBytes();
}
