// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/v1/entity.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.v1;

public final class EntityProto {
  private EntityProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      EntityProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_PromptFilterResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_PromptFilterResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_ErrorBase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_ErrorBase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_ContentFilterPromptResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_ContentFilterPromptResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_ContentFilterSeverityResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_ContentFilterSeverityResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_ContentFilterDetectedResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_ContentFilterDetectedResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_Citation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_Citation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n msp/azure/openai/v1/entity.proto\022\023msp." +
      "azure.openai.v1\"\221\001\n\022PromptFilterResult\022\024" +
      "\n\005index\030\001 \001(\rR\005index\022e\n\025content_filter_r" +
      "esult\030\002 \001(\0132..msp.azure.openai.v1.Conten" +
      "tFilterPromptResultR\026content_filter_resu" +
      "lts\"9\n\tErrorBase\022\022\n\004code\030\001 \001(\tR\004code\022\030\n\007" +
      "message\030\002 \001(\tR\007message\"\236\004\n\031ContentFilter" +
      "PromptResult\022H\n\006sexual\030\001 \001(\01320.msp.azure" +
      ".openai.v1.ContentFilterSeverityResultR\006" +
      "sexual\022L\n\010violence\030\002 \001(\01320.msp.azure.ope" +
      "nai.v1.ContentFilterSeverityResultR\010viol" +
      "ence\022D\n\004hate\030\003 \001(\01320.msp.azure.openai.v1" +
      ".ContentFilterSeverityResultR\004hate\022M\n\tse" +
      "lf_harm\030\004 \001(\01320.msp.azure.openai.v1.Cont" +
      "entFilterSeverityResultR\010selfHarm\022N\n\tpro" +
      "fanity\030\005 \001(\01320.msp.azure.openai.v1.Conte" +
      "ntFilterDetectedResultR\tprofanity\022N\n\tjai" +
      "lbreak\030\006 \001(\01320.msp.azure.openai.v1.Conte" +
      "ntFilterDetectedResultR\tjailbreak\0224\n\005err" +
      "or\030c \001(\0132\036.msp.azure.openai.v1.ErrorBase" +
      "R\005error\"\256\005\n\031ContentFilterChoiceResult\022H\n" +
      "\006sexual\030\001 \001(\01320.msp.azure.openai.v1.Cont" +
      "entFilterSeverityResultR\006sexual\022L\n\010viole" +
      "nce\030\002 \001(\01320.msp.azure.openai.v1.ContentF" +
      "ilterSeverityResultR\010violence\022D\n\004hate\030\003 " +
      "\001(\01320.msp.azure.openai.v1.ContentFilterS" +
      "everityResultR\004hate\022M\n\tself_harm\030\004 \001(\01320" +
      ".msp.azure.openai.v1.ContentFilterSeveri" +
      "tyResultR\010selfHarm\022N\n\tprofanity\030\005 \001(\01320." +
      "msp.azure.openai.v1.ContentFilterDetecte" +
      "dResultR\tprofanity\022h\n\027protected_material" +
      "_text\030\006 \001(\01320.msp.azure.openai.v1.Conten" +
      "tFilterDetectedResultR\025protectedMaterial" +
      "Text\022t\n\027protected_material_code\030\007 \001(\0132<." +
      "msp.azure.openai.v1.ContentFilterDetecte" +
      "dWithCitationResultR\025protectedMaterialCo" +
      "de\0224\n\005error\030c \001(\0132\036.msp.azure.openai.v1." +
      "ErrorBaseR\005error\"U\n\033ContentFilterSeverit" +
      "yResult\022\032\n\010filtered\030\001 \001(\010R\010filtered\022\032\n\010s" +
      "everity\030\002 \001(\tR\010severity\"U\n\033ContentFilter" +
      "DetectedResult\022\032\n\010filtered\030\001 \001(\010R\010filter" +
      "ed\022\032\n\010detected\030\002 \001(\tR\010detected\"\374\001\n\'Conte" +
      "ntFilterDetectedWithCitationResult\022\032\n\010fi" +
      "ltered\030\001 \001(\010R\010filtered\022\032\n\010detected\030\002 \001(\010" +
      "R\010detected\022a\n\010citation\030\003 \001(\0132E.msp.azure" +
      ".openai.v1.ContentFilterDetectedWithCita" +
      "tionResult.CitationR\010citation\0326\n\010Citatio" +
      "n\022\020\n\003url\030\001 \001(\tR\003url\022\030\n\007license\030\002 \001(\tR\007li" +
      "censeB\332\001\n\027com.msp.azure.openai.v1B\013Entit" +
      "yProtoP\001ZCgithub.com/anaregdesign/azure-" +
      "proto/go/msp/azure/openai/v1;openaiv1\242\002\003" +
      "MAO\252\002\023Msp.Azure.Openai.V1\312\002\023Msp\\Azure\\Op" +
      "enai\\V1\342\002\037Msp\\Azure\\Openai\\V1\\GPBMetadat" +
      "a\352\002\026Msp::Azure::Openai::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_msp_azure_openai_v1_PromptFilterResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msp_azure_openai_v1_PromptFilterResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_PromptFilterResult_descriptor,
        new java.lang.String[] { "Index", "ContentFilterResult", });
    internal_static_msp_azure_openai_v1_ErrorBase_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msp_azure_openai_v1_ErrorBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_ErrorBase_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_msp_azure_openai_v1_ContentFilterPromptResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_msp_azure_openai_v1_ContentFilterPromptResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_ContentFilterPromptResult_descriptor,
        new java.lang.String[] { "Sexual", "Violence", "Hate", "SelfHarm", "Profanity", "Jailbreak", "Error", });
    internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_ContentFilterChoiceResult_descriptor,
        new java.lang.String[] { "Sexual", "Violence", "Hate", "SelfHarm", "Profanity", "ProtectedMaterialText", "ProtectedMaterialCode", "Error", });
    internal_static_msp_azure_openai_v1_ContentFilterSeverityResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_msp_azure_openai_v1_ContentFilterSeverityResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_ContentFilterSeverityResult_descriptor,
        new java.lang.String[] { "Filtered", "Severity", });
    internal_static_msp_azure_openai_v1_ContentFilterDetectedResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_msp_azure_openai_v1_ContentFilterDetectedResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_ContentFilterDetectedResult_descriptor,
        new java.lang.String[] { "Filtered", "Detected", });
    internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_descriptor,
        new java.lang.String[] { "Filtered", "Detected", "Citation", });
    internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_Citation_descriptor =
      internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_descriptor.getNestedTypes().get(0);
    internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_Citation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msp_azure_openai_v1_ContentFilterDetectedWithCitationResult_Citation_descriptor,
        new java.lang.String[] { "Url", "License", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
