// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: msp/azure/openai/v1/embeddings.proto

package openaiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input     string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	User      string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	InputType string `protobuf:"bytes,3,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_msp_azure_openai_v1_embeddings_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *EmbeddingRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EmbeddingRequest) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object string                    `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Model  string                    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Data   []*EmbeddingResponse_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Usage  *EmbeddingResponse_Usage  `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_msp_azure_openai_v1_embeddings_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EmbeddingResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingResponse) GetData() []*EmbeddingResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmbeddingResponse) GetUsage() *EmbeddingResponse_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type EmbeddingResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     uint32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Object    string    `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Embedding []float32 `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
}

func (x *EmbeddingResponse_Data) Reset() {
	*x = EmbeddingResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddingResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse_Data) ProtoMessage() {}

func (x *EmbeddingResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse_Data.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse_Data) Descriptor() ([]byte, []int) {
	return file_msp_azure_openai_v1_embeddings_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EmbeddingResponse_Data) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EmbeddingResponse_Data) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EmbeddingResponse_Data) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type EmbeddingResponse_Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromptTokens uint32 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	TotalTokens  uint32 `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
}

func (x *EmbeddingResponse_Usage) Reset() {
	*x = EmbeddingResponse_Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddingResponse_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse_Usage) ProtoMessage() {}

func (x *EmbeddingResponse_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_msp_azure_openai_v1_embeddings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse_Usage.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse_Usage) Descriptor() ([]byte, []int) {
	return file_msp_azure_openai_v1_embeddings_proto_rawDescGZIP(), []int{1, 1}
}

func (x *EmbeddingResponse_Usage) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *EmbeddingResponse_Usage) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_msp_azure_openai_v1_embeddings_proto protoreflect.FileDescriptor

var file_msp_azure_openai_v1_embeddings_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x73, 0x70, 0x2f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6d, 0x73, 0x70, 0x2e, 0x61, 0x7a, 0x75, 0x72,
	0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x5b, 0x0a, 0x10, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xeb, 0x02, 0x0a, 0x11, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x3f, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x73, 0x70,
	0x2e, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x42, 0x0a,
	0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d,
	0x73, 0x70, 0x2e, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x52, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x1a, 0x4f, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x42, 0xde, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x6d,
	0x73, 0x70, 0x2e, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x2e,
	0x76, 0x31, 0x42, 0x0f, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6e, 0x61, 0x72, 0x65, 0x67, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x61,
	0x7a, 0x75, 0x72, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x73,
	0x70, 0x2f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x2f, 0x76,
	0x31, 0x3b, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4d, 0x41, 0x4f,
	0xaa, 0x02, 0x13, 0x4d, 0x73, 0x70, 0x2e, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x61, 0x69, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x13, 0x4d, 0x73, 0x70, 0x5c, 0x41, 0x7a, 0x75,
	0x72, 0x65, 0x5c, 0x4f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1f, 0x4d,
	0x73, 0x70, 0x5c, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x5c, 0x4f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x16, 0x4d, 0x73, 0x70, 0x3a, 0x3a, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x3a, 0x3a, 0x4f, 0x70, 0x65,
	0x6e, 0x61, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msp_azure_openai_v1_embeddings_proto_rawDescOnce sync.Once
	file_msp_azure_openai_v1_embeddings_proto_rawDescData = file_msp_azure_openai_v1_embeddings_proto_rawDesc
)

func file_msp_azure_openai_v1_embeddings_proto_rawDescGZIP() []byte {
	file_msp_azure_openai_v1_embeddings_proto_rawDescOnce.Do(func() {
		file_msp_azure_openai_v1_embeddings_proto_rawDescData = protoimpl.X.CompressGZIP(file_msp_azure_openai_v1_embeddings_proto_rawDescData)
	})
	return file_msp_azure_openai_v1_embeddings_proto_rawDescData
}

var file_msp_azure_openai_v1_embeddings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msp_azure_openai_v1_embeddings_proto_goTypes = []interface{}{
	(*EmbeddingRequest)(nil),        // 0: msp.azure.openai.v1.EmbeddingRequest
	(*EmbeddingResponse)(nil),       // 1: msp.azure.openai.v1.EmbeddingResponse
	(*EmbeddingResponse_Data)(nil),  // 2: msp.azure.openai.v1.EmbeddingResponse.Data
	(*EmbeddingResponse_Usage)(nil), // 3: msp.azure.openai.v1.EmbeddingResponse.Usage
}
var file_msp_azure_openai_v1_embeddings_proto_depIdxs = []int32{
	2, // 0: msp.azure.openai.v1.EmbeddingResponse.data:type_name -> msp.azure.openai.v1.EmbeddingResponse.Data
	3, // 1: msp.azure.openai.v1.EmbeddingResponse.usage:type_name -> msp.azure.openai.v1.EmbeddingResponse.Usage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msp_azure_openai_v1_embeddings_proto_init() }
func file_msp_azure_openai_v1_embeddings_proto_init() {
	if File_msp_azure_openai_v1_embeddings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msp_azure_openai_v1_embeddings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbeddingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msp_azure_openai_v1_embeddings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbeddingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msp_azure_openai_v1_embeddings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbeddingResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msp_azure_openai_v1_embeddings_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbeddingResponse_Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msp_azure_openai_v1_embeddings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msp_azure_openai_v1_embeddings_proto_goTypes,
		DependencyIndexes: file_msp_azure_openai_v1_embeddings_proto_depIdxs,
		MessageInfos:      file_msp_azure_openai_v1_embeddings_proto_msgTypes,
	}.Build()
	File_msp_azure_openai_v1_embeddings_proto = out.File
	file_msp_azure_openai_v1_embeddings_proto_rawDesc = nil
	file_msp_azure_openai_v1_embeddings_proto_goTypes = nil
	file_msp_azure_openai_v1_embeddings_proto_depIdxs = nil
}
