// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msp/azure/openai/assistants/v1/assistants.proto
// Protobuf Java Version: 4.27.0

package com.msp.azure.openai.assistants.v1;

/**
 * Protobuf type {@code msp.azure.openai.assistants.v1.CreateAssistantRequest}
 */
public final class CreateAssistantRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:msp.azure.openai.assistants.v1.CreateAssistantRequest)
    CreateAssistantRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      CreateAssistantRequest.class.getName());
  }
  // Use CreateAssistantRequest.newBuilder() to construct.
  private CreateAssistantRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateAssistantRequest() {
    model_ = "";
    name_ = "";
    description_ = "";
    instruction_ = "";
    tools_ = java.util.Collections.emptyList();
    fileIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    responseFormat_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msp.azure.openai.assistants.v1.AssistantsProto.internal_static_msp_azure_openai_assistants_v1_CreateAssistantRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 7:
        return internalGetMetadata();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msp.azure.openai.assistants.v1.AssistantsProto.internal_static_msp_azure_openai_assistants_v1_CreateAssistantRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msp.azure.openai.assistants.v1.CreateAssistantRequest.class, com.msp.azure.openai.assistants.v1.CreateAssistantRequest.Builder.class);
  }

  public static final int MODEL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object model_ = "";
  /**
   * <code>string model = 1 [json_name = "model"];</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>string model = 1 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTRUCTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instruction_ = "";
  /**
   * <code>string instruction = 4 [json_name = "instructions"];</code>
   * @return The instruction.
   */
  @java.lang.Override
  public java.lang.String getInstruction() {
    java.lang.Object ref = instruction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instruction_ = s;
      return s;
    }
  }
  /**
   * <code>string instruction = 4 [json_name = "instructions"];</code>
   * @return The bytes for instruction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstructionBytes() {
    java.lang.Object ref = instruction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instruction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOOLS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.msp.azure.openai.assistants.v1.Tool> tools_;
  /**
   * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
   */
  @java.lang.Override
  public java.util.List<com.msp.azure.openai.assistants.v1.Tool> getToolsList() {
    return tools_;
  }
  /**
   * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.msp.azure.openai.assistants.v1.ToolOrBuilder> 
      getToolsOrBuilderList() {
    return tools_;
  }
  /**
   * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
   */
  @java.lang.Override
  public int getToolsCount() {
    return tools_.size();
  }
  /**
   * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.assistants.v1.Tool getTools(int index) {
    return tools_.get(index);
  }
  /**
   * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
   */
  @java.lang.Override
  public com.msp.azure.openai.assistants.v1.ToolOrBuilder getToolsOrBuilder(
      int index) {
    return tools_.get(index);
  }

  public static final int FILE_IDS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList fileIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
   * @return A list containing the fileIds.
   */
  public com.google.protobuf.ProtocolStringList
      getFileIdsList() {
    return fileIds_;
  }
  /**
   * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
   * @return The count of fileIds.
   */
  public int getFileIdsCount() {
    return fileIds_.size();
  }
  /**
   * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
   * @param index The index of the element to return.
   * @return The fileIds at the given index.
   */
  public java.lang.String getFileIds(int index) {
    return fileIds_.get(index);
  }
  /**
   * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the fileIds at the given index.
   */
  public com.google.protobuf.ByteString
      getFileIdsBytes(int index) {
    return fileIds_.getByteString(index);
  }

  public static final int METADATA_FIELD_NUMBER = 7;
  private static final class MetadataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.msp.azure.openai.assistants.v1.AssistantsProto.internal_static_msp_azure_openai_assistants_v1_CreateAssistantRequest_MetadataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metadata_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetadata() {
    if (metadata_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetadataDefaultEntryHolder.defaultEntry);
    }
    return metadata_;
  }
  public int getMetadataCount() {
    return internalGetMetadata().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public boolean containsMetadata(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetadata().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
    return getMetadataMap();
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
    return internalGetMetadata().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public java.lang.String getMetadataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 8;
  private float temperature_ = 0F;
  /**
   * <code>float temperature = 8 [json_name = "temperature"];</code>
   * @return The temperature.
   */
  @java.lang.Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int TOP_P_FIELD_NUMBER = 9;
  private float topP_ = 0F;
  /**
   * <code>float top_p = 9 [json_name = "topP"];</code>
   * @return The topP.
   */
  @java.lang.Override
  public float getTopP() {
    return topP_;
  }

  public static final int RESPONSE_FORMAT_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object responseFormat_ = "";
  /**
   * <code>string response_format = 10 [json_name = "responseFormat"];</code>
   * @return The responseFormat.
   */
  @java.lang.Override
  public java.lang.String getResponseFormat() {
    java.lang.Object ref = responseFormat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseFormat_ = s;
      return s;
    }
  }
  /**
   * <code>string response_format = 10 [json_name = "responseFormat"];</code>
   * @return The bytes for responseFormat.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponseFormatBytes() {
    java.lang.Object ref = responseFormat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseFormat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, model_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instruction_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, instruction_);
    }
    for (int i = 0; i < tools_.size(); i++) {
      output.writeMessage(5, tools_.get(i));
    }
    for (int i = 0; i < fileIds_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, fileIds_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetMetadata(),
        MetadataDefaultEntryHolder.defaultEntry,
        7);
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      output.writeFloat(8, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(topP_) != 0) {
      output.writeFloat(9, topP_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseFormat_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, responseFormat_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(model_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, model_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instruction_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, instruction_);
    }
    for (int i = 0; i < tools_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, tools_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < fileIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(fileIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFileIdsList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetadata().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, metadata__);
    }
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(topP_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(9, topP_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseFormat_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, responseFormat_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msp.azure.openai.assistants.v1.CreateAssistantRequest)) {
      return super.equals(obj);
    }
    com.msp.azure.openai.assistants.v1.CreateAssistantRequest other = (com.msp.azure.openai.assistants.v1.CreateAssistantRequest) obj;

    if (!getModel()
        .equals(other.getModel())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getInstruction()
        .equals(other.getInstruction())) return false;
    if (!getToolsList()
        .equals(other.getToolsList())) return false;
    if (!getFileIdsList()
        .equals(other.getFileIdsList())) return false;
    if (!internalGetMetadata().equals(
        other.internalGetMetadata())) return false;
    if (java.lang.Float.floatToIntBits(getTemperature())
        != java.lang.Float.floatToIntBits(
            other.getTemperature())) return false;
    if (java.lang.Float.floatToIntBits(getTopP())
        != java.lang.Float.floatToIntBits(
            other.getTopP())) return false;
    if (!getResponseFormat()
        .equals(other.getResponseFormat())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
    hash = (53 * hash) + getInstruction().hashCode();
    if (getToolsCount() > 0) {
      hash = (37 * hash) + TOOLS_FIELD_NUMBER;
      hash = (53 * hash) + getToolsList().hashCode();
    }
    if (getFileIdsCount() > 0) {
      hash = (37 * hash) + FILE_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getFileIdsList().hashCode();
    }
    if (!internalGetMetadata().getMap().isEmpty()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetadata().hashCode();
    }
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + TOP_P_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTopP());
    hash = (37 * hash) + RESPONSE_FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getResponseFormat().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msp.azure.openai.assistants.v1.CreateAssistantRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code msp.azure.openai.assistants.v1.CreateAssistantRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:msp.azure.openai.assistants.v1.CreateAssistantRequest)
      com.msp.azure.openai.assistants.v1.CreateAssistantRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msp.azure.openai.assistants.v1.AssistantsProto.internal_static_msp_azure_openai_assistants_v1_CreateAssistantRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msp.azure.openai.assistants.v1.AssistantsProto.internal_static_msp_azure_openai_assistants_v1_CreateAssistantRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msp.azure.openai.assistants.v1.CreateAssistantRequest.class, com.msp.azure.openai.assistants.v1.CreateAssistantRequest.Builder.class);
    }

    // Construct using com.msp.azure.openai.assistants.v1.CreateAssistantRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      model_ = "";
      name_ = "";
      description_ = "";
      instruction_ = "";
      if (toolsBuilder_ == null) {
        tools_ = java.util.Collections.emptyList();
      } else {
        tools_ = null;
        toolsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      fileIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableMetadata().clear();
      temperature_ = 0F;
      topP_ = 0F;
      responseFormat_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msp.azure.openai.assistants.v1.AssistantsProto.internal_static_msp_azure_openai_assistants_v1_CreateAssistantRequest_descriptor;
    }

    @java.lang.Override
    public com.msp.azure.openai.assistants.v1.CreateAssistantRequest getDefaultInstanceForType() {
      return com.msp.azure.openai.assistants.v1.CreateAssistantRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.msp.azure.openai.assistants.v1.CreateAssistantRequest build() {
      com.msp.azure.openai.assistants.v1.CreateAssistantRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msp.azure.openai.assistants.v1.CreateAssistantRequest buildPartial() {
      com.msp.azure.openai.assistants.v1.CreateAssistantRequest result = new com.msp.azure.openai.assistants.v1.CreateAssistantRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.msp.azure.openai.assistants.v1.CreateAssistantRequest result) {
      if (toolsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          tools_ = java.util.Collections.unmodifiableList(tools_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.tools_ = tools_;
      } else {
        result.tools_ = toolsBuilder_.build();
      }
    }

    private void buildPartial0(com.msp.azure.openai.assistants.v1.CreateAssistantRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.model_ = model_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.instruction_ = instruction_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        fileIds_.makeImmutable();
        result.fileIds_ = fileIds_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.temperature_ = temperature_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.topP_ = topP_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.responseFormat_ = responseFormat_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msp.azure.openai.assistants.v1.CreateAssistantRequest) {
        return mergeFrom((com.msp.azure.openai.assistants.v1.CreateAssistantRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msp.azure.openai.assistants.v1.CreateAssistantRequest other) {
      if (other == com.msp.azure.openai.assistants.v1.CreateAssistantRequest.getDefaultInstance()) return this;
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getInstruction().isEmpty()) {
        instruction_ = other.instruction_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (toolsBuilder_ == null) {
        if (!other.tools_.isEmpty()) {
          if (tools_.isEmpty()) {
            tools_ = other.tools_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureToolsIsMutable();
            tools_.addAll(other.tools_);
          }
          onChanged();
        }
      } else {
        if (!other.tools_.isEmpty()) {
          if (toolsBuilder_.isEmpty()) {
            toolsBuilder_.dispose();
            toolsBuilder_ = null;
            tools_ = other.tools_;
            bitField0_ = (bitField0_ & ~0x00000010);
            toolsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getToolsFieldBuilder() : null;
          } else {
            toolsBuilder_.addAllMessages(other.tools_);
          }
        }
      }
      if (!other.fileIds_.isEmpty()) {
        if (fileIds_.isEmpty()) {
          fileIds_ = other.fileIds_;
          bitField0_ |= 0x00000020;
        } else {
          ensureFileIdsIsMutable();
          fileIds_.addAll(other.fileIds_);
        }
        onChanged();
      }
      internalGetMutableMetadata().mergeFrom(
          other.internalGetMetadata());
      bitField0_ |= 0x00000040;
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getTopP() != 0F) {
        setTopP(other.getTopP());
      }
      if (!other.getResponseFormat().isEmpty()) {
        responseFormat_ = other.responseFormat_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              model_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              instruction_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              com.msp.azure.openai.assistants.v1.Tool m =
                  input.readMessage(
                      com.msp.azure.openai.assistants.v1.Tool.parser(),
                      extensionRegistry);
              if (toolsBuilder_ == null) {
                ensureToolsIsMutable();
                tools_.add(m);
              } else {
                toolsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFileIdsIsMutable();
              fileIds_.add(s);
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetadata().getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 69: {
              temperature_ = input.readFloat();
              bitField0_ |= 0x00000080;
              break;
            } // case 69
            case 77: {
              topP_ = input.readFloat();
              bitField0_ |= 0x00000100;
              break;
            } // case 77
            case 82: {
              responseFormat_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object model_ = "";
    /**
     * <code>string model = 1 [json_name = "model"];</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model = 1 [json_name = "model"];</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model = 1 [json_name = "model"];</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      model_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string model = 1 [json_name = "model"];</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      model_ = getDefaultInstance().getModel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string model = 1 [json_name = "model"];</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      model_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object instruction_ = "";
    /**
     * <code>string instruction = 4 [json_name = "instructions"];</code>
     * @return The instruction.
     */
    public java.lang.String getInstruction() {
      java.lang.Object ref = instruction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instruction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instruction = 4 [json_name = "instructions"];</code>
     * @return The bytes for instruction.
     */
    public com.google.protobuf.ByteString
        getInstructionBytes() {
      java.lang.Object ref = instruction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instruction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instruction = 4 [json_name = "instructions"];</code>
     * @param value The instruction to set.
     * @return This builder for chaining.
     */
    public Builder setInstruction(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instruction_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string instruction = 4 [json_name = "instructions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInstruction() {
      instruction_ = getDefaultInstance().getInstruction();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string instruction = 4 [json_name = "instructions"];</code>
     * @param value The bytes for instruction to set.
     * @return This builder for chaining.
     */
    public Builder setInstructionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instruction_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<com.msp.azure.openai.assistants.v1.Tool> tools_ =
      java.util.Collections.emptyList();
    private void ensureToolsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        tools_ = new java.util.ArrayList<com.msp.azure.openai.assistants.v1.Tool>(tools_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.msp.azure.openai.assistants.v1.Tool, com.msp.azure.openai.assistants.v1.Tool.Builder, com.msp.azure.openai.assistants.v1.ToolOrBuilder> toolsBuilder_;

    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public java.util.List<com.msp.azure.openai.assistants.v1.Tool> getToolsList() {
      if (toolsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tools_);
      } else {
        return toolsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public int getToolsCount() {
      if (toolsBuilder_ == null) {
        return tools_.size();
      } else {
        return toolsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public com.msp.azure.openai.assistants.v1.Tool getTools(int index) {
      if (toolsBuilder_ == null) {
        return tools_.get(index);
      } else {
        return toolsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder setTools(
        int index, com.msp.azure.openai.assistants.v1.Tool value) {
      if (toolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToolsIsMutable();
        tools_.set(index, value);
        onChanged();
      } else {
        toolsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder setTools(
        int index, com.msp.azure.openai.assistants.v1.Tool.Builder builderForValue) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.set(index, builderForValue.build());
        onChanged();
      } else {
        toolsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder addTools(com.msp.azure.openai.assistants.v1.Tool value) {
      if (toolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToolsIsMutable();
        tools_.add(value);
        onChanged();
      } else {
        toolsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder addTools(
        int index, com.msp.azure.openai.assistants.v1.Tool value) {
      if (toolsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureToolsIsMutable();
        tools_.add(index, value);
        onChanged();
      } else {
        toolsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder addTools(
        com.msp.azure.openai.assistants.v1.Tool.Builder builderForValue) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.add(builderForValue.build());
        onChanged();
      } else {
        toolsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder addTools(
        int index, com.msp.azure.openai.assistants.v1.Tool.Builder builderForValue) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.add(index, builderForValue.build());
        onChanged();
      } else {
        toolsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder addAllTools(
        java.lang.Iterable<? extends com.msp.azure.openai.assistants.v1.Tool> values) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tools_);
        onChanged();
      } else {
        toolsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder clearTools() {
      if (toolsBuilder_ == null) {
        tools_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        toolsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public Builder removeTools(int index) {
      if (toolsBuilder_ == null) {
        ensureToolsIsMutable();
        tools_.remove(index);
        onChanged();
      } else {
        toolsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public com.msp.azure.openai.assistants.v1.Tool.Builder getToolsBuilder(
        int index) {
      return getToolsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public com.msp.azure.openai.assistants.v1.ToolOrBuilder getToolsOrBuilder(
        int index) {
      if (toolsBuilder_ == null) {
        return tools_.get(index);  } else {
        return toolsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public java.util.List<? extends com.msp.azure.openai.assistants.v1.ToolOrBuilder> 
         getToolsOrBuilderList() {
      if (toolsBuilder_ != null) {
        return toolsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tools_);
      }
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public com.msp.azure.openai.assistants.v1.Tool.Builder addToolsBuilder() {
      return getToolsFieldBuilder().addBuilder(
          com.msp.azure.openai.assistants.v1.Tool.getDefaultInstance());
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public com.msp.azure.openai.assistants.v1.Tool.Builder addToolsBuilder(
        int index) {
      return getToolsFieldBuilder().addBuilder(
          index, com.msp.azure.openai.assistants.v1.Tool.getDefaultInstance());
    }
    /**
     * <code>repeated .msp.azure.openai.assistants.v1.Tool tools = 5 [json_name = "tools"];</code>
     */
    public java.util.List<com.msp.azure.openai.assistants.v1.Tool.Builder> 
         getToolsBuilderList() {
      return getToolsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.msp.azure.openai.assistants.v1.Tool, com.msp.azure.openai.assistants.v1.Tool.Builder, com.msp.azure.openai.assistants.v1.ToolOrBuilder> 
        getToolsFieldBuilder() {
      if (toolsBuilder_ == null) {
        toolsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.msp.azure.openai.assistants.v1.Tool, com.msp.azure.openai.assistants.v1.Tool.Builder, com.msp.azure.openai.assistants.v1.ToolOrBuilder>(
                tools_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        tools_ = null;
      }
      return toolsBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList fileIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFileIdsIsMutable() {
      if (!fileIds_.isModifiable()) {
        fileIds_ = new com.google.protobuf.LazyStringArrayList(fileIds_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @return A list containing the fileIds.
     */
    public com.google.protobuf.ProtocolStringList
        getFileIdsList() {
      fileIds_.makeImmutable();
      return fileIds_;
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @return The count of fileIds.
     */
    public int getFileIdsCount() {
      return fileIds_.size();
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @param index The index of the element to return.
     * @return The fileIds at the given index.
     */
    public java.lang.String getFileIds(int index) {
      return fileIds_.get(index);
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the fileIds at the given index.
     */
    public com.google.protobuf.ByteString
        getFileIdsBytes(int index) {
      return fileIds_.getByteString(index);
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @param index The index to set the value at.
     * @param value The fileIds to set.
     * @return This builder for chaining.
     */
    public Builder setFileIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFileIdsIsMutable();
      fileIds_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @param value The fileIds to add.
     * @return This builder for chaining.
     */
    public Builder addFileIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFileIdsIsMutable();
      fileIds_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @param values The fileIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllFileIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureFileIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fileIds_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFileIds() {
      fileIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_ids = 6 [json_name = "fileIds"];</code>
     * @param value The bytes of the fileIds to add.
     * @return This builder for chaining.
     */
    public Builder addFileIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFileIdsIsMutable();
      fileIds_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetadata() {
      if (metadata_ == null) {
        metadata_ = com.google.protobuf.MapField.newMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      if (!metadata_.isMutable()) {
        metadata_ = metadata_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return metadata_;
    }
    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableMetadata().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
     */
    public Builder removeMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetadata().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetadata() {
      bitField0_ |= 0x00000040;
      return internalGetMutableMetadata().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
     */
    public Builder putMetadata(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetadata().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [json_name = "metadata"];</code>
     */
    public Builder putAllMetadata(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetadata().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }

    private float temperature_ ;
    /**
     * <code>float temperature = 8 [json_name = "temperature"];</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <code>float temperature = 8 [json_name = "temperature"];</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {

      temperature_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature = 8 [json_name = "temperature"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000080);
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float topP_ ;
    /**
     * <code>float top_p = 9 [json_name = "topP"];</code>
     * @return The topP.
     */
    @java.lang.Override
    public float getTopP() {
      return topP_;
    }
    /**
     * <code>float top_p = 9 [json_name = "topP"];</code>
     * @param value The topP to set.
     * @return This builder for chaining.
     */
    public Builder setTopP(float value) {

      topP_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>float top_p = 9 [json_name = "topP"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTopP() {
      bitField0_ = (bitField0_ & ~0x00000100);
      topP_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object responseFormat_ = "";
    /**
     * <code>string response_format = 10 [json_name = "responseFormat"];</code>
     * @return The responseFormat.
     */
    public java.lang.String getResponseFormat() {
      java.lang.Object ref = responseFormat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseFormat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string response_format = 10 [json_name = "responseFormat"];</code>
     * @return The bytes for responseFormat.
     */
    public com.google.protobuf.ByteString
        getResponseFormatBytes() {
      java.lang.Object ref = responseFormat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string response_format = 10 [json_name = "responseFormat"];</code>
     * @param value The responseFormat to set.
     * @return This builder for chaining.
     */
    public Builder setResponseFormat(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      responseFormat_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string response_format = 10 [json_name = "responseFormat"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseFormat() {
      responseFormat_ = getDefaultInstance().getResponseFormat();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string response_format = 10 [json_name = "responseFormat"];</code>
     * @param value The bytes for responseFormat to set.
     * @return This builder for chaining.
     */
    public Builder setResponseFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      responseFormat_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:msp.azure.openai.assistants.v1.CreateAssistantRequest)
  }

  // @@protoc_insertion_point(class_scope:msp.azure.openai.assistants.v1.CreateAssistantRequest)
  private static final com.msp.azure.openai.assistants.v1.CreateAssistantRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msp.azure.openai.assistants.v1.CreateAssistantRequest();
  }

  public static com.msp.azure.openai.assistants.v1.CreateAssistantRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAssistantRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateAssistantRequest>() {
    @java.lang.Override
    public CreateAssistantRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateAssistantRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAssistantRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msp.azure.openai.assistants.v1.CreateAssistantRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

